name: 'Meteor Docker'

inputs:
  CR_USER:
    required: true
  CR_PAT:
    required: true
  node-version:
    required: true
    description: 'Node version'
    type: string
  deno-version:
    required: true
    description: 'Deno version'
    type: string
  platform:
    required: false
    description: 'Platform'
    default: 'alpine'
  arch:
    required: false
    description: 'Architecture'
    default: 'amd64'
  build-containers:
    required: false
    description: 'Containers to build along with Rocket.Chat'
    type: string
  turbo-cache:
    required: false
    description: 'Enable turbo cache'
    default: 'true'
  publish-image:
    required: false
    description: 'Publish image'
    default: 'true'
  setup:
    required: false
    description: 'Setup node.js'
    default: 'true'
  NPM_TOKEN:
    required: false
    description: 'NPM token'

runs:
  using: composite

  steps:
    # - name: Install system dependencies
    #   shell: bash
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y build-essential libpng-dev autoconf automake libtool

    - name: Login to GitHub Container Registry
      if: inputs.publish-image == 'true' && github.actor != 'dependabot[bot]' && (github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'release' || github.ref == 'refs/heads/develop')
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.CR_USER }}
        password: ${{ inputs.CR_PAT }}

    - name: Restore packages build
      uses: actions/download-artifact@v4
      with:
        name: packages-build
        path: /tmp

    - name: Unpack packages build
      shell: bash
      run: |
        tar -xzf /tmp/RocketChat-packages-build.tar.gz -C .

    - name: Restore meteor build
      if: inputs.build-containers == 'rocketchat'
      uses: actions/download-artifact@v4
      with:
        name: build
        path: /tmp/build

    - name: Unpack meteor build
      if: inputs.build-containers == 'rocketchat'
      shell: bash
      run: |
        cd /tmp/build
        tar xzf Rocket.Chat.tar.gz
        rm Rocket.Chat.tar.gz

    # - uses: rharkor/caching-for-turbo@v1.8
    #   # if we are testing a PR from a fork, we already called the turbo cache at this point, so it should be false
    #   if: inputs.turbo-cache == 'true'

    # - name: Setup NodeJS
    #   uses: ./.github/actions/setup-node
    #   if: inputs.setup == 'true'
    #   with:
    #     node-version: ${{ inputs.node-version }}
    #     deno-version: ${{ inputs.deno-version }}
    #     cache-modules: true
    #     install: true
    #     NPM_TOKEN: ${{ inputs.NPM_TOKEN }}

    # - name: Restore turbo build
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: turbo-build
    #     path: .turbo/cache

    # - run: yarn build
    #   if: inputs.setup == 'true'
    #   shell: bash

    - name: Set up Docker
      uses: docker/setup-docker-action@v4
      with:
        daemon-config: |
          {
            "debug": true,
            "features": {
              "containerd-snapshotter": true
            }
          }

    # - uses: docker/setup-qemu-action@v3
    #   with:
    #     platforms: arm64
    #     # image: tonistiigi/binfmt:qemu-v10.0.4
    #     image: tonistiigi/binfmt:qemu-v8.1.5

    # - name: Config QEMU
    #   shell: bash
    #   run: echo "QEMU_CPU=max" >> $GITHUB_ENV

    - uses: docker/setup-buildx-action@v3
      with:
        # driver-opts: |
        #   image=moby/buildkit:v0.13.3
        buildkitd-flags: --oci-worker-gc --oci-worker-gc-keepstorage=4000

    - name: Build Docker images
      shell: bash
      run: |
        args=(${{ inputs.build-containers }})

        export DENO_VERSION="${{ inputs.deno-version }}"

        docker buildx bake -f docker-compose-ci.yml --load --allow=fs.read=/tmp/build --set *.platform=linux/${{ inputs.arch }} --set *.cache-from=type=gha --set *.cache-to=type=gha,mode=max "${args[@]}"

    - name: Publish Docker images to GitHub Container Registry
      if: inputs.publish-image == 'true' && github.actor != 'dependabot[bot]' && (github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'release' || github.ref == 'refs/heads/develop')
      shell: bash
      run: |
        args=(${{ inputs.build-containers }})

        docker compose -f docker-compose-ci.yml push "${args[@]}"
        # docker buildx bake -f docker-compose-ci.yml --push --set *.cache-from=type=gha --set *.cache-to=type=gha,mode=max "${args[@]}"

    - name: Debug BuildKit container
      if: failure()
      shell: bash
      run: |
        docker ps -a --filter "name=buildx_buildkit" || true
        ID=$(docker ps -a --filter "name=buildx_buildkit" --format "{{.ID}}" | head -n1)
        if [ -n "$ID" ]; then
          echo "Logs do BuildKit ($ID):"
          docker logs --tail 200 "$ID" || true
        fi

    - name: Clean up temporary files
      if: inputs.build-containers == 'rocketchat'
      shell: bash
      run: |
        sudo rm -rf /tmp/build
