export const countries = [
    { code: 'US', name: 'United States', dialCode: '+1' },
    { code: 'CA', name: 'Canada', dialCode: '+1' },
    { code: 'GB', name: 'United Kingdom', dialCode: '+44' },
    { code: 'AU', name: 'Australia', dialCode: '+61' },
    { code: 'DE', name: 'Germany', dialCode: '+49' },
    { code: 'FR', name: 'France', dialCode: '+33' },
    { code: 'IN', name: 'India', dialCode: '+91' },
    { code: 'CN', name: 'China', dialCode: '+86' },
    { code: 'JP', name: 'Japan', dialCode: '+81' },
    { code: 'BR', name: 'Brazil', dialCode: '+55' },
    { code: 'MX', name: 'Mexico', dialCode: '+52' },
    { code: 'ES', name: 'Spain', dialCode: '+34' },
    { code: 'IT', name: 'Italy', dialCode: '+39' },
    { code: 'RU', name: 'Russia', dialCode: '+7' },
    { code: 'ZA', name: 'South Africa', dialCode: '+27' },
    { code: 'NG', name: 'Nigeria', dialCode: '+234' },
    { code: 'AE', name: 'United Arab Emirates', dialCode: '+971' },
    { code: 'SA', name: 'Saudi Arabia', dialCode: '+966' },
    { code: 'SG', name: 'Singapore', dialCode: '+65' },
    { code: 'HK', name: 'Hong Kong', dialCode: '+852' },
    { code: 'KR', name: 'South Korea', dialCode: '+82' },
];
