"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VideoConfProviderNotRegisteredError = exports.VideoConfProviderAlreadyExistsError = exports.InvalidLicenseError = exports.RequiredApiVersionError = exports.NotEnoughMethodArgumentsError = exports.MustExtendAppError = exports.MustContainFunctionError = exports.CompilerError = exports.PathAlreadyExistsError = exports.CommandHasAlreadyBeenTouchedError = exports.CommandAlreadyExistsError = void 0;
const CommandAlreadyExistsError_1 = require("./CommandAlreadyExistsError");
Object.defineProperty(exports, "CommandAlreadyExistsError", { enumerable: true, get: function () { return CommandAlreadyExistsError_1.CommandAlreadyExistsError; } });
const CommandHasAlreadyBeenTouchedError_1 = require("./CommandHasAlreadyBeenTouchedError");
Object.defineProperty(exports, "CommandHasAlreadyBeenTouchedError", { enumerable: true, get: function () { return CommandHasAlreadyBeenTouchedError_1.CommandHasAlreadyBeenTouchedError; } });
const CompilerError_1 = require("./CompilerError");
Object.defineProperty(exports, "CompilerError", { enumerable: true, get: function () { return CompilerError_1.CompilerError; } });
const InvalidLicenseError_1 = require("./InvalidLicenseError");
Object.defineProperty(exports, "InvalidLicenseError", { enumerable: true, get: function () { return InvalidLicenseError_1.InvalidLicenseError; } });
const MustContainFunctionError_1 = require("./MustContainFunctionError");
Object.defineProperty(exports, "MustContainFunctionError", { enumerable: true, get: function () { return MustContainFunctionError_1.MustContainFunctionError; } });
const MustExtendAppError_1 = require("./MustExtendAppError");
Object.defineProperty(exports, "MustExtendAppError", { enumerable: true, get: function () { return MustExtendAppError_1.MustExtendAppError; } });
const NotEnoughMethodArgumentsError_1 = require("./NotEnoughMethodArgumentsError");
Object.defineProperty(exports, "NotEnoughMethodArgumentsError", { enumerable: true, get: function () { return NotEnoughMethodArgumentsError_1.NotEnoughMethodArgumentsError; } });
const PathAlreadyExistsError_1 = require("./PathAlreadyExistsError");
Object.defineProperty(exports, "PathAlreadyExistsError", { enumerable: true, get: function () { return PathAlreadyExistsError_1.PathAlreadyExistsError; } });
const RequiredApiVersionError_1 = require("./RequiredApiVersionError");
Object.defineProperty(exports, "RequiredApiVersionError", { enumerable: true, get: function () { return RequiredApiVersionError_1.RequiredApiVersionError; } });
const VideoConfProviderAlreadyExistsError_1 = require("./VideoConfProviderAlreadyExistsError");
Object.defineProperty(exports, "VideoConfProviderAlreadyExistsError", { enumerable: true, get: function () { return VideoConfProviderAlreadyExistsError_1.VideoConfProviderAlreadyExistsError; } });
const VideoConfProviderNotRegisteredError_1 = require("./VideoConfProviderNotRegisteredError");
Object.defineProperty(exports, "VideoConfProviderNotRegisteredError", { enumerable: true, get: function () { return VideoConfProviderNotRegisteredError_1.VideoConfProviderNotRegisteredError; } });
//# sourceMappingURL=index.js.map