{
 "title": "Rocket.Chat Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(nodejs_active_handles_total,app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rocketchat_users_online{app=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Users Away",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rocketchat_users_away{app=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "DDP Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocketchat_ddp_connected_users{app=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rocketchat_users_total{app=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rocketchat_rooms_total{app=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rocketchat_messages_total{app=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Users Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "max(rocketchat_users_total{app=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Rooms  Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "max(rocketchat_rooms_total{app=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Messages  Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "max(rocketchat_messages_total{app=\"$deployment\"})"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Metrics Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rocketchat_metrics_requests{app=\"$deployment\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metrics Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rocketchat_metrics_size{app=\"$deployment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "NodeJS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{app=\"$deployment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_requests_total{app=\"$deployment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{app=\"$deployment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (space) (nodejs_heap_size_used_bytes{app=\"$deployment\"})",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Per pod heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{app=\"$deployment\"}",
     "legendFormat": "{{instance}} [{{space}}]"
    }
   ]
  },
  {
   "title": "GC - Seconds Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nodejs_gc_pause_seconds_total{app=\"$deployment\"}[5m])) by (gctype)",
     "legendFormat": "{{gctype}}"
    }
   ]
  },
  {
   "title": "GC - Bytes Freed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nodejs_gc_reclaimed_bytes_total{app=\"$deployment\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DDP Rate Limiter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Limit by type",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{app=\"$deployment\", user_id!=\"null\"}[5m])) by (limit_name)",
       "legendFormat": "{{limit_name}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{app=\"$deployment\", user_id=\"null\"}[5m])) by (limit_name)",
       "legendFormat": "{{limit_name}} (null)"
      }
     ]
    },
    {
     "title": "Limit by method",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{app=\"$deployment\", user_id!=\"null\"}[5m])) by (type,name)",
       "legendFormat": "{{type}}: {{name}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{app=\"$deployment\", user_id=\"null\"}[5m])) by (type,name)",
       "legendFormat": "{{type}}: {{name}} (null)"
      }
     ]
    },
    {
     "title": "Limit by userId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{app=\"$deployment\"}[5m])) by (user_id)",
       "legendFormat": "{{user_id}}"
      }
     ]
    },
    {
     "title": "Limit by connectionId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{app=\"$deployment\", user_id!=\"null\"}[5m])) by (connection_id)",
       "legendFormat": "{{connection_id}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{app=\"$deployment\", user_id=\"null\"}[5m])) by (connection_id)",
       "legendFormat": "{{connection_id}} (null)"
      }
     ]
    }
   ]
  },
  { "title": "RocketChat Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Messages Sent (30m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rocketchat_message_sent{app=\"$deployment\"}[30m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages Sent Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rocketchat_messages_total{app=\"$deployment\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages Round Trip",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(rocketchat_messages_roundtrip_time{app=\"$deployment\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Users Presence",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rocketchat_users_online{app=\"$deployment\"})",
     "legendFormat": "Online"
    },
    {
     "expr": "avg(rocketchat_users_away{app=\"$deployment\"})",
     "legendFormat": "Away"
    }
   ]
  },
  {
   "title": "Users & Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_ddp_connected_users{app=\"$Deployment\"})",
     "legendFormat": "Connected Users"
    },
    {
     "expr": "sum(rocketchat_ddp_sessions_count{app=\"$deployment\"})",
     "legendFormat": "All Sessions"
    },
    {
     "expr": "sum(rocketchat_ddp_sessions_auth{app=\"$deployment\"})",
     "legendFormat": "Authenticated Sessions "
    }
   ]
  },
  {
   "title": "Web Socket Connections per pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketchat_ddp_connected_users{app=\"$deployment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Apps Installed / Disabled / Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketchat_apps_installed{app=\"$deployment\"}",
     "legendFormat": "{{instance}} - installed"
    },
    {
     "expr": "rocketchat_apps_enabled{app=\"$deployment\"}",
     "legendFormat": "{{instance}} - enabled"
    },
    {
     "expr": "rocketchat_apps_failed{app=\"$deployment\"}",
     "legendFormat": "{{instance}} - failed"
    }
   ]
  },
  {
   "title": "Oplog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(rocketchat_oplog{app=\"$deployment\"}[5m])) by (collection,op)",
     "legendFormat": "{{collection}}/{{op}}"
    }
   ]
  },
  {
   "title": "Oplog By instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(rocketchat_oplog{app=\"$deployment\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketchat_oplog_queue{app=\"$deployment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Push Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketchat_push_queue{app=\"$deployment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Meteor Facts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_facts{app=\"$deployment\"}) by (pkg, fact)",
     "legendFormat": "{{pkg}} {{fact}}"
    }
   ]
  },
  {
   "title": "Total of Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "max(rocketchat_users_total{app=\"$deployment\"})",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Total of Rooms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "max(rocketchat_rooms_total{app=\"$deployment\"})",
     "legendFormat": "Rooms"
    }
   ]
  },
  {
   "title": "Notifications / Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_notification_sent{app=\"$deployment\"}[5m])) by (notification_type)",
     "legendFormat": "{{notification_type}}"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meteor Methods Total Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_methods{app=\"$deployment\"}) by (method) * sum(increase(rocketchat_meteor_methods_count{app=\"$deployment\"}[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Meteor Methods Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_methods{app=\"$deployment\"}) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Meteor Methods Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_meteor_methods_count{app=\"$deployment\"}[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meteor Subscription Total Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_subscriptions{app=\"$deployment\"}) by (subscription) * sum(increase(rocketchat_meteor_subscriptions_count{app=\"$deployment\"}[5m])) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Meteor Subscription Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_subscriptions{app=\"$deployment\"}) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Meteor Subscription Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_meteor_subscriptions_count{app=\"$deployment\"}[5m])) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Callbacks & Hooks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 },
   "collapsed": true,
   "panels": [
    {
     "title": "Callbacks Total Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_callbacks{app=\"$deployment\"}) by (callback) * sum(increase(rocketchat_callbacks_count{app=\"$deployment\"}[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Callbacks Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_callbacks{app=\"$deployment\"}[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Callbacks Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_callbacks_count{app=\"$deployment\"}[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Hooks Total Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_hooks{app=\"$deployment\"}) by (hook) * sum(increase(rocketchat_hooks_count{app=\"$deployment\"}[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    },
    {
     "title": "Hooks Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_hooks{app=\"$deployment\"}[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    },
    {
     "title": "Hooks Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_hooks_count{app=\"$deployment\"}[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 },
   "collapsed": true,
   "panels": [
    {
     "title": "REST API Total Times",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_rest_api{app=\"$deployment\"}) by (entrypoint) * sum(increase(rocketchat_rest_api_count{app=\"$deployment\"}[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "REST API Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_rest_api{app=\"$deployment\"}[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "REST API Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_rest_api_count{app=\"$deployment\"}[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    }
   ]
  }
 ]
}