export enum E2ERoomState {
	NO_PASSWORD_SET = 'NO_PASSWORD_SET',
	NOT_STARTED = 'NOT_STARTED',
	DISABLED = 'DISABLED',
	HANDSHAKE = 'HANDSHAKE',
	ESTABLISHING = 'ESTABLISHING',
	CREATING_KEYS = 'CREATING_KEYS',
	WAITING_KEYS = 'WAITING_KEYS',
	KEYS_RECEIVED = 'KEYS_RECEIVED',
	READY = 'READY',
	ERROR = 'ERROR',
}
