export const DEV_DB_EXIT_CODES = {
	OK: 0,
	INVALID_ARGUMENT: 10,
	LOCK_CONFLICT: 11,
	LOCK_STALE: 12,
	STATE_INVALID: 13,
	BACKEND_NOT_AVAILABLE: 20,
	BACKEND_NOT_IMPLEMENTED: 21,
	HEALTH_TCP_FAILED: 30,
	HEALTH_PING_FAILED: 31,
	HEALTH_WRITABLE_PRIMARY_FAILED: 32,
	UNEXPECTED_ERROR: 90,
} as const;

export type DevDbExitCode = (typeof DEV_DB_EXIT_CODES)[keyof typeof DEV_DB_EXIT_CODES];
