import './Analytics';
import './Avatars';
// import './Banners';
// import './BannersDismiss';
import './CredentialTokens';
import './CustomSounds';
import './CustomUserStatus';
import './EmailInbox';
import './EmailMessageHistory';
import './EmojiCustom';
import './ExportOperations';
import './FederationServers';
import './ImportData';
import './InstanceStatus';
import './IntegrationHistory';
import './Integrations';
import './Invites';
