name: 'Setup Node'

inputs:
  node-version:
    required: true
    type: string
  cache-modules:
    required: false
    type: boolean
  install:
    required: false
    type: boolean
  deno-version:
    required: true
    type: string
  deno-dir:
    required: false
    type: string
    default: ~/.deno-cache

outputs:
  node-version:
    value: ${{ steps.node-version.outputs.node-version }}

runs:
  using: composite

  steps:
    - run: echo 'DENO_DIR=${{ inputs.deno-dir }}' >> $GITHUB_ENV
      shell: bash

    - name: Cache Node Modules & Deno
      if: inputs.cache-modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ${{ env.DENO_DIR }}
          apps/meteor/node_modules
          apps/meteor/ee/server/services/node_modules
        key: node-modules-${{ hashFiles('yarn.lock') }}-deno-${{ hashFiles('packages/apps-engine/deno-runtime/deno.lock') }}
    #
    # Could use this command to list all paths to save:
    # find . -name 'node_modules' -prune | grep -v "/\.meteor/" | grep -v "/meteor/packages/"

    - name: Use Node.js ${{ inputs.node-version }}
      id: node-version
      uses: actions/setup-node@v3.7.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

    - name: Use Deno ${{ inputs.deno-version }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ inputs.deno-version }}

    - name: yarn install
      shell: bash
      run: yarn
