/**
 * Which group each operation belongs to in the published documentation, imported from
 * RocketChat/Rocket.Chat-Open-API. Kept here rather than in the route options: options are part
 * of the type every caller of the endpoint sees, and this many tags collapse it.
 */
export const operationTags: Record<string, string[]> = {
	'delete /api/v1/abac/attributes/{_id}': ['ABAC'],
	'delete /api/v1/abac/rooms/{rid}/attributes': ['ABAC'],
	'delete /api/v1/abac/rooms/{rid}/attributes/{key}': ['ABAC'],
	'delete /api/v1/email-inbox/{_id}': ['Email Inbox'],
	'delete /api/v1/push.token': ['Push Notifications'],
	'delete /api/v1/removeInvite/{_id}': ['Room Invites'],
	'get /api/v1/abac/attributes': ['ABAC'],
	'get /api/v1/abac/attributes/{_id}': ['ABAC'],
	'get /api/v1/abac/attributes/{key}/is-in-use': ['ABAC'],
	'get /api/v1/abac/audit': ['ABAC'],
	'get /api/v1/abac/pdp/health': ['ABAC'],
	'get /api/v1/abac/rooms': ['ABAC'],
	'get /api/v1/audit/rooms.members': ['Rooms'],
	'get /api/v1/autotranslate.getSupportedLanguages': ['Auto-Translate'],
	'get /api/v1/banners': ['Banners'],
	'get /api/v1/banners/{id}': ['Banners'],
	'get /api/v1/calendar-events.info': ['Calendar Events'],
	'get /api/v1/calendar-events.list': ['Calendar Events'],
	'get /api/v1/channels.anonymousread': ['Channels'],
	'get /api/v1/channels.counters': ['Channels'],
	'get /api/v1/channels.files': ['Channels'],
	'get /api/v1/channels.getAllUserMentionsByChannel': ['Channels'],
	'get /api/v1/channels.getIntegrations': ['Channels'],
	'get /api/v1/channels.history': ['Channels'],
	'get /api/v1/channels.info': ['Channels'],
	'get /api/v1/channels.list': ['Channels'],
	'get /api/v1/channels.list.joined': ['Channels'],
	'get /api/v1/channels.members': ['Channels'],
	'get /api/v1/channels.messages': ['Channels'],
	'get /api/v1/channels.moderators': ['Channels'],
	'get /api/v1/channels.online': ['Channels'],
	'get /api/v1/channels.roles': ['Channels'],
	'get /api/v1/chat.getDeletedMessages': ['Chat'],
	'get /api/v1/chat.getDiscussions': ['Chat'],
	'get /api/v1/chat.getMentionedMessages': ['Chat'],
	'get /api/v1/chat.getMessage': ['Chat'],
	'get /api/v1/chat.getMessageReadReceipts': ['Chat'],
	'get /api/v1/chat.getPinnedMessages': ['Chat'],
	'get /api/v1/chat.getStarredMessages': ['Chat'],
	'get /api/v1/chat.getThreadMessages': ['Chat'],
	'get /api/v1/chat.getThreadsList': ['Chat'],
	'get /api/v1/chat.getURLPreview': ['Chat'],
	'get /api/v1/chat.ignoreUser': ['Chat'],
	'get /api/v1/chat.search': ['Chat'],
	'get /api/v1/chat.syncMessages': ['Chat'],
	'get /api/v1/chat.syncThreadMessages': ['Chat'],
	'get /api/v1/chat.syncThreadsList': ['Chat'],
	'get /api/v1/cloud.registrationStatus': ['Cloud'],
	'get /api/v1/commands.get': ['Commands'],
	'get /api/v1/commands.list': ['Commands'],
	'get /api/v1/commands.preview': ['Commands'],
	'get /api/v1/custom-sounds.getOne': ['Custom Sounds'],
	'get /api/v1/custom-sounds.list': ['Custom Sounds'],
	'get /api/v1/custom-user-status.list': ['Custom User Status'],
	'get /api/v1/directory': ['Directory'],
	'get /api/v1/dm.counters': ['Direct Messages'],
	'get /api/v1/dm.files': ['Direct Messages'],
	'get /api/v1/dm.history': ['Direct Messages'],
	'get /api/v1/dm.list': ['Direct Messages'],
	'get /api/v1/dm.list.everyone': ['Direct Messages'],
	'get /api/v1/dm.members': ['Direct Messages'],
	'get /api/v1/dm.messages': ['Direct Messages'],
	'get /api/v1/dm.messages.others': ['Direct Messages'],
	'get /api/v1/e2e.fetchMyKeys': ['E2E'],
	'get /api/v1/e2e.getUsersOfRoomWithoutKey': ['E2E'],
	'get /api/v1/email-inbox.list': ['Email Inbox'],
	'get /api/v1/email-inbox.search': ['Email Inbox'],
	'get /api/v1/email-inbox/{_id}': ['Email Inbox'],
	'get /api/v1/emoji-custom.all': ['Custom Emoji'],
	'get /api/v1/emoji-custom.list': ['Custom Emoji'],
	'get /api/v1/engagement-dashboard/channels/list': ['Channels Engagement'],
	'get /api/v1/engagement-dashboard/messages/messages-sent': ['Messages Engagement'],
	'get /api/v1/engagement-dashboard/messages/origin': ['Messages Engagement'],
	'get /api/v1/engagement-dashboard/messages/top-five-popular-channels': ['Messages Engagement'],
	'get /api/v1/engagement-dashboard/users/active-users': ['Users Engagement'],
	'get /api/v1/engagement-dashboard/users/chat-busier/hourly-data': ['Users Engagement'],
	'get /api/v1/engagement-dashboard/users/chat-busier/weekly-data': ['Users Engagement'],
	'get /api/v1/engagement-dashboard/users/new-users': ['Users Engagement'],
	'get /api/v1/engagement-dashboard/users/users-by-time-of-the-day-in-a-week': ['Users Engagement'],
	'get /api/v1/getCurrentImportOperation': ['Import'],
	'get /api/v1/getImportFileData': ['Import'],
	'get /api/v1/getImportProgress': ['Import'],
	'get /api/v1/getLatestImportOperations': ['Import'],
	'get /api/v1/im.counters': ['Direct Messages'],
	'get /api/v1/im.files': ['Direct Messages'],
	'get /api/v1/im.history': ['Direct Messages'],
	'get /api/v1/im.list': ['Direct Messages'],
	'get /api/v1/im.list.everyone': ['Direct Messages'],
	'get /api/v1/im.members': ['Direct Messages'],
	'get /api/v1/im.messages': ['Direct Messages'],
	'get /api/v1/im.messages.others': ['Direct Messages'],
	'get /api/v1/import.status': ['Bulk User Import'],
	'get /api/v1/importers.list': ['Import'],
	'get /api/v1/instances.get': ['Instances'],
	'get /api/v1/integrations.get': ['Integration'],
	'get /api/v1/integrations.history': ['Integration'],
	'get /api/v1/integrations.list': ['Integration'],
	'get /api/v1/listInvites': ['Room Invites'],
	'get /api/v1/livechat/config/routing': ['Livechat'],
	'get /api/v1/me': ['Authentication'],
	'get /api/v1/moderation.reportInfo': ['Moderation'],
	'get /api/v1/moderation.reports': ['Moderation'],
	'get /api/v1/moderation.reportsByUsers': ['Moderation'],
	'get /api/v1/moderation.user.reportedMessages': ['Moderation'],
	'get /api/v1/moderation.user.reportsByUserId': ['Moderation'],
	'get /api/v1/moderation.userReports': ['Moderation'],
	'get /api/v1/oauth-apps.get': ['OAuth Apps'],
	'get /api/v1/oauth-apps.list': ['OAuth Apps'],
	'get /api/v1/permissions.listAll': ['Permissions'],
	'get /api/v1/push.get': ['Push Notifications'],
	'get /api/v1/push.info': ['Push Notifications'],
	'get /api/v1/pw.getPolicy': ['Password policy'],
	'get /api/v1/roles.getUsersInPublicRoles': ['Roles'],
	'get /api/v1/roles.getUsersInRole': ['Roles'],
	'get /api/v1/roles.list': ['Roles'],
	'get /api/v1/roles.sync': ['Roles'],
	'get /api/v1/rooms.adminRooms': ['Rooms'],
	'get /api/v1/rooms.adminRooms.getRoom': ['Rooms'],
	'get /api/v1/rooms.autocomplete.adminRooms': ['Rooms'],
	'get /api/v1/rooms.autocomplete.availableForTeams': ['Rooms'],
	'get /api/v1/rooms.autocomplete.channelAndPrivate': ['Rooms'],
	'get /api/v1/rooms.autocomplete.channelAndPrivate.withPagination': ['Rooms'],
	'get /api/v1/rooms.get': ['Rooms'],
	'get /api/v1/rooms.getDiscussions': ['Rooms'],
	'get /api/v1/rooms.images': ['Rooms'],
	'get /api/v1/rooms.info': ['Rooms'],
	'get /api/v1/rooms.isMember': ['Rooms'],
	'get /api/v1/rooms.membersOrderedByRole': ['Rooms'],
	'get /api/v1/rooms.nameExists': ['Rooms'],
	'get /api/v1/rooms.roles': ['Rooms'],
	'get /api/v1/service.configurations': ['Settings'],
	'get /api/v1/settings': ['Settings'],
	'get /api/v1/settings.oauth': ['Settings'],
	'get /api/v1/settings.public': ['Settings'],
	'get /api/v1/settings/{_id}': ['Settings'],
	'get /api/v1/statistics': ['Statistics'],
	'get /api/v1/statistics.list': ['Statistics'],
	'get /api/v1/subscriptions.get': ['Subscriptions'],
	'get /api/v1/subscriptions.getOne': ['Subscriptions'],
	'get /api/v1/teams.autocomplete': ['Teams'],
	'get /api/v1/teams.info': ['Teams'],
	'get /api/v1/teams.list': ['Teams'],
	'get /api/v1/teams.listAll': ['Teams'],
	'get /api/v1/teams.listChildren': ['Teams'],
	'get /api/v1/teams.listRooms': ['Teams'],
	'get /api/v1/teams.listRoomsOfUser': ['Teams'],
	'get /api/v1/teams.members': ['Teams'],
	'get /api/v1/users.autocomplete': ['Users'],
	'get /api/v1/users.checkUsernameAvailability': ['Users'],
	'get /api/v1/users.getAvatarSuggestion': ['Users'],
	'get /api/v1/users.getPersonalAccessTokens': ['Users'],
	'get /api/v1/users.getPreferences': ['Users'],
	'get /api/v1/users.getPresence': ['Users'],
	'get /api/v1/users.getStatus': ['Users'],
	'get /api/v1/users.getUsernameSuggestion': ['Users'],
	'get /api/v1/users.info': ['Users'],
	'get /api/v1/users.listByStatus': ['Users'],
	'get /api/v1/users.listTeams': ['Users'],
	'get /api/v1/users.presence': ['Users'],
	'get /api/v1/users.requestDataDownload': ['Users'],
	'get /api/v1/video-conference.capabilities': ['Video Conference'],
	'get /api/v1/video-conference.info': ['Video Conference'],
	'get /api/v1/video-conference.list': ['Video Conference'],
	'get /api/v1/video-conference.providers': ['Video Conference'],
	'get /api/v1/webdav.getMyAccounts': ['WebDAV'],
	'post /api/v1/abac/attributes': ['ABAC'],
	'post /api/v1/abac/rooms/{rid}/attributes': ['ABAC'],
	'post /api/v1/abac/rooms/{rid}/attributes/{key}': ['ABAC'],
	'post /api/v1/abac/users/sync': ['ABAC'],
	'post /api/v1/assets.setAsset': ['Assets'],
	'post /api/v1/assets.unsetAsset': ['Assets'],
	'post /api/v1/autotranslate.saveSettings': ['Auto-Translate'],
	'post /api/v1/autotranslate.translateMessage': ['Auto-Translate'],
	'post /api/v1/banners.dismiss': ['Banners'],
	'post /api/v1/calendar-events.create': ['Calendar Events'],
	'post /api/v1/calendar-events.delete': ['Calendar Events'],
	'post /api/v1/calendar-events.import': ['Calendar Events'],
	'post /api/v1/calendar-events.update': ['Calendar Events'],
	'post /api/v1/channels.addAll': ['Channels'],
	'post /api/v1/channels.addLeader': ['Channels'],
	'post /api/v1/channels.addModerator': ['Channels'],
	'post /api/v1/channels.addOwner': ['Channels'],
	'post /api/v1/channels.archive': ['Channels'],
	'post /api/v1/channels.close': ['Channels'],
	'post /api/v1/channels.convertToTeam': ['Channels'],
	'post /api/v1/channels.create': ['Channels'],
	'post /api/v1/channels.delete': ['Channels'],
	'post /api/v1/channels.invite': ['Channels'],
	'post /api/v1/channels.join': ['Channels'],
	'post /api/v1/channels.kick': ['Channels'],
	'post /api/v1/channels.leave': ['Channels'],
	'post /api/v1/channels.open': ['Channels'],
	'post /api/v1/channels.removeLeader': ['Channels'],
	'post /api/v1/channels.removeModerator': ['Channels'],
	'post /api/v1/channels.removeOwner': ['Channels'],
	'post /api/v1/channels.rename': ['Channels'],
	'post /api/v1/channels.setAnnouncement': ['Channels'],
	'post /api/v1/channels.setCustomFields': ['Channels'],
	'post /api/v1/channels.setDefault': ['Channels'],
	'post /api/v1/channels.setDescription': ['Channels'],
	'post /api/v1/channels.setJoinCode': ['Channels'],
	'post /api/v1/channels.setPurpose': ['Channels'],
	'post /api/v1/channels.setReadOnly': ['Channels'],
	'post /api/v1/channels.setTopic': ['Channels'],
	'post /api/v1/channels.setType': ['Channels'],
	'post /api/v1/channels.unarchive': ['Channels'],
	'post /api/v1/chat.delete': ['Chat'],
	'post /api/v1/chat.followMessage': ['Chat'],
	'post /api/v1/chat.pinMessage': ['Chat'],
	'post /api/v1/chat.postMessage': ['Chat'],
	'post /api/v1/chat.react': ['Chat'],
	'post /api/v1/chat.reportMessage': ['Chat'],
	'post /api/v1/chat.sendMessage': ['Chat'],
	'post /api/v1/chat.starMessage': ['Chat'],
	'post /api/v1/chat.unfollowMessage': ['Chat'],
	'post /api/v1/chat.unPinMessage': ['Chat'],
	'post /api/v1/chat.unStarMessage': ['Chat'],
	'post /api/v1/chat.update': ['Chat'],
	'post /api/v1/cloud.connectWorkspace': ['Cloud'],
	'post /api/v1/cloud.manualRegister': ['Cloud'],
	'post /api/v1/commands.preview': ['Commands'],
	'post /api/v1/commands.run': ['Commands'],
	'post /api/v1/custom-sounds.create': ['Custom Sounds'],
	'post /api/v1/custom-sounds.delete': ['Custom Sounds'],
	'post /api/v1/custom-sounds.update': ['Custom Sounds'],
	'post /api/v1/custom-user-status.create': ['Custom User Status'],
	'post /api/v1/custom-user-status.delete': ['Custom User Status'],
	'post /api/v1/custom-user-status.update': ['Custom User Status'],
	'post /api/v1/dm.blockUser': ['Direct Messages'],
	'post /api/v1/dm.close': ['Direct Messages'],
	'post /api/v1/dm.create': ['Direct Messages'],
	'post /api/v1/dm.delete': ['Direct Messages'],
	'post /api/v1/dm.open': ['Direct Messages'],
	'post /api/v1/dm.setTopic': ['Direct Messages'],
	'post /api/v1/downloadPendingAvatars': ['Import'],
	'post /api/v1/downloadPendingFiles': ['Import'],
	'post /api/v1/downloadPublicImportFile': ['Import'],
	'post /api/v1/e2e.requestSubscriptionKeys': ['E2E'],
	'post /api/v1/e2e.setRoomKeyID': ['E2E'],
	'post /api/v1/e2e.setUserPublicAndPrivateKeys': ['E2E'],
	'post /api/v1/e2e.updateGroupKey': ['E2E'],
	'post /api/v1/email-inbox': ['Email Inbox'],
	'post /api/v1/emoji-custom.create': ['Custom Emoji'],
	'post /api/v1/emoji-custom.delete': ['Custom Emoji'],
	'post /api/v1/emoji-custom.update': ['Custom Emoji'],
	'post /api/v1/findOrCreateInvite': ['Room Invites'],
	'post /api/v1/groups.addAll': ['Groups'],
	'post /api/v1/groups.addLeader': ['Groups'],
	'post /api/v1/groups.addModerator': ['Groups'],
	'post /api/v1/groups.addOwner': ['Groups'],
	'post /api/v1/groups.archive': ['Groups'],
	'post /api/v1/groups.close': ['Groups'],
	'post /api/v1/groups.kick': ['Groups'],
	'post /api/v1/groups.leave': ['Groups'],
	'post /api/v1/groups.open': ['Groups'],
	'post /api/v1/groups.removeLeader': ['Groups'],
	'post /api/v1/groups.removeModerator': ['Groups'],
	'post /api/v1/groups.removeOwner': ['Groups'],
	'post /api/v1/groups.rename': ['Groups'],
	'post /api/v1/groups.setAnnouncement': ['Groups'],
	'post /api/v1/groups.setCustomFields': ['Groups'],
	'post /api/v1/groups.setDescription': ['Groups'],
	'post /api/v1/groups.setEncrypted': ['Groups'],
	'post /api/v1/groups.setPurpose': ['Groups'],
	'post /api/v1/groups.setReadOnly': ['Groups'],
	'post /api/v1/groups.setTopic': ['Groups'],
	'post /api/v1/groups.setType': ['Groups'],
	'post /api/v1/groups.unarchive': ['Groups'],
	'post /api/v1/im.blockUser': ['Direct Messages'],
	'post /api/v1/im.close': ['Direct Messages'],
	'post /api/v1/im.create': ['Direct Messages'],
	'post /api/v1/im.delete': ['Direct Messages'],
	'post /api/v1/im.open': ['Direct Messages'],
	'post /api/v1/im.setTopic': ['Direct Messages'],
	'post /api/v1/import.addUsers': ['Bulk User Import'],
	'post /api/v1/import.clear': ['Bulk User Import'],
	'post /api/v1/import.new': ['Bulk User Import'],
	'post /api/v1/import.run': ['Bulk User Import'],
	'post /api/v1/integrations.clearHistory': ['Integration'],
	'post /api/v1/integrations.create': ['Integration'],
	'post /api/v1/integrations.remove': ['Integration'],
	'post /api/v1/integrations.replayOutgoing': ['Integration'],
	'post /api/v1/ldap.syncNow': ['LDAP'],
	'post /api/v1/ldap.testConnection': ['LDAP'],
	'post /api/v1/ldap.testSearch': ['LDAP'],
	'post /api/v1/livechat/agents.saveInfo': ['Omnichannel Agents'],
	'post /api/v1/livechat/business-hours.remove': ['Omnichannel Business Hours'],
	'post /api/v1/livechat/business-hours.save': ['Omnichannel Business Hours'],
	'post /api/v1/livechat/custom-fields.delete': ['Omnichannel Custom Fields'],
	'post /api/v1/livechat/custom-fields.save': ['Omnichannel Custom Fields'],
	'post /api/v1/livechat/inquiries.returnAsInquiry': ['Omnichannel Inquiries'],
	'post /api/v1/livechat/monitors.create': ['Omnichannel Monitors'],
	'post /api/v1/livechat/monitors.delete': ['Omnichannel Monitors'],
	'post /api/v1/livechat/rooms.delete': ['Omnichannel Rooms'],
	'post /api/v1/livechat/rooms.removeAllClosedRooms': ['Omnichannel Rooms'],
	'post /api/v1/livechat/tags.delete': ['Omnichannel Tags'],
	'post /api/v1/livechat/tags.save': ['Omnichannel Tags'],
	'post /api/v1/livechat/visitor/department.transfer': ['Omnichannel Rooms'],
	'post /api/v1/loginCode.redeem': ['Authentication'],
	'post /api/v1/mailer': ['Mailer'],
	'post /api/v1/mailer.unsubscribe': ['Mailer'],
	'post /api/v1/moderation.dismissReports': ['Moderation'],
	'post /api/v1/moderation.dismissUserReports': ['Moderation'],
	'post /api/v1/moderation.reportUser': ['Users'],
	'post /api/v1/moderation.user.deleteReportedMessages': ['Moderation'],
	'post /api/v1/oauth-apps.create': ['OAuth Apps'],
	'post /api/v1/oauth-apps.delete': ['OAuth Apps'],
	'post /api/v1/oauth-apps.update': ['OAuth Apps'],
	'post /api/v1/permissions.addRole': ['Permissions'],
	'post /api/v1/permissions.removeRole': ['Permissions'],
	'post /api/v1/permissions.update': ['Permissions'],
	'post /api/v1/push.test': ['Push Notifications'],
	'post /api/v1/push.token': ['Push Notifications'],
	'post /api/v1/roles.addUserToRole': ['Roles'],
	'post /api/v1/roles.delete': ['Roles'],
	'post /api/v1/roles.removeUserFromRole': ['Roles'],
	'post /api/v1/rooms.changeArchivationState': ['Rooms'],
	'post /api/v1/rooms.cleanHistory': ['Rooms'],
	'post /api/v1/rooms.createDiscussion': ['Rooms'],
	'post /api/v1/rooms.delete': ['Rooms'],
	'post /api/v1/rooms.export': ['Rooms'],
	'post /api/v1/rooms.favorite': ['Rooms'],
	'post /api/v1/rooms.hide': ['Rooms'],
	'post /api/v1/rooms.join': ['Rooms'],
	'post /api/v1/rooms.leave': ['Rooms'],
	'post /api/v1/rooms.muteUser': ['Rooms'],
	'post /api/v1/rooms.saveNotification': ['Rooms'],
	'post /api/v1/rooms.saveRoomSettings': ['Rooms'],
	'post /api/v1/rooms.unmuteUser': ['Rooms'],
	'post /api/v1/sendInvitationEmail': ['Users'],
	'post /api/v1/settings': ['Settings'],
	'post /api/v1/settings.addCustomOAuth': ['Settings'],
	'post /api/v1/settings/{_id}': ['Settings'],
	'post /api/v1/startImport': ['Import'],
	'post /api/v1/subscriptions.read': ['Subscriptions'],
	'post /api/v1/subscriptions.unread': ['Subscriptions'],
	'post /api/v1/teams.addMembers': ['Teams'],
	'post /api/v1/teams.addRooms': ['Teams'],
	'post /api/v1/teams.convertToChannel': ['Teams'],
	'post /api/v1/teams.create': ['Teams'],
	'post /api/v1/teams.delete': ['Teams'],
	'post /api/v1/teams.leave': ['Teams'],
	'post /api/v1/teams.removeMember': ['Teams'],
	'post /api/v1/teams.removeRoom': ['Teams'],
	'post /api/v1/teams.update': ['Teams'],
	'post /api/v1/teams.updateMember': ['Teams'],
	'post /api/v1/teams.updateRoom': ['Teams'],
	'post /api/v1/uploadImportFile': ['Import'],
	'post /api/v1/uploads.delete': ['Rooms'],
	'post /api/v1/useInviteToken': ['Room Invites'],
	'post /api/v1/users.2fa.disableEmail': ['Two-Factor Authentication'],
	'post /api/v1/users.2fa.enableEmail': ['Two-Factor Authentication'],
	'post /api/v1/users.2fa.sendEmailCode': ['Two-Factor Authentication'],
	'post /api/v1/users.create': ['Users'],
	'post /api/v1/users.createToken': ['Users'],
	'post /api/v1/users.deactivateIdle': ['Users'],
	'post /api/v1/users.delete': ['Users'],
	'post /api/v1/users.deleteOwnAccount': ['Users'],
	'post /api/v1/users.forgotPassword': ['Users'],
	'post /api/v1/users.generatePersonalAccessToken': ['Users'],
	'post /api/v1/users.logout': ['Users'],
	'post /api/v1/users.logoutOtherClients': ['Users'],
	'post /api/v1/users.regeneratePersonalAccessToken': ['Users'],
	'post /api/v1/users.register': ['Users'],
	'post /api/v1/users.removeOtherTokens': ['Users'],
	'post /api/v1/users.removePersonalAccessToken': ['Users'],
	'post /api/v1/users.resetAvatar': ['Users'],
	'post /api/v1/users.resetE2EKey': ['Users'],
	'post /api/v1/users.resetTOTP': ['Users'],
	'post /api/v1/users.sendConfirmationEmail': ['Users'],
	'post /api/v1/users.sendWelcomeEmail': ['Users'],
	'post /api/v1/users.setActiveStatus': ['Users'],
	'post /api/v1/users.setAvatar': ['Users'],
	'post /api/v1/users.setPreferences': ['Users'],
	'post /api/v1/users.setStatus': ['Users'],
	'post /api/v1/users.update': ['Users'],
	'post /api/v1/users.updateOwnBasicInfo': ['Users'],
	'post /api/v1/users.verifyEmail': ['Users'],
	'post /api/v1/video-conference.cancel': ['Video Conference'],
	'post /api/v1/video-conference.join': ['Video Conference'],
	'post /api/v1/video-conference.start': ['Video Conference'],
	'post /api/v1/webdav.removeWebdavAccount': ['WebDAV'],
	'put /api/v1/abac/attributes/{_id}': ['ABAC'],
	'put /api/v1/abac/rooms/{rid}/attributes/{key}': ['ABAC'],
	'put /api/v1/integrations.update': ['Integration'],
};
