pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/.meteor/
      - ./node_modules
      - ./.meteor/local
    volumes:
      - /tmp/cache/Rocket.Chat:/cache
    when:
        event: push
        branch:
          - staging
          - master
  build:
    image: ubuntu:16.04
    environment:
      - METEOR_ALLOW_SUPERUSER=true
    commands:
      - apt update && apt install curl git python g++ build-essential bzip2 -y
      - export HOME=/drone
      - export PATH="/drone/.meteor:$PATH"
      - if [ ! -e "/drone/.meteor/meteor" ]; then export HOME=/drone; curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh; fi
      - which meteor
      - meteor npm install
      - set +e
      - meteor add rocketchat:lib
      - set -e
      - mkdir /drone/build
      - meteor build --allow-superuser --server-only --directory /drone/build
    when:
        event: push
        branch:
          - staging
          - master
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/.meteor/
      - ./node_modules
      - ./.meteor/local
    volumes:
      - /tmp/cache/Rocket.Chat:/cache
    when:
        event: push
        branch:
          - staging
          - master
  s3-sync-dist-test:
      image: plugins/s3-sync:1
      secrets:
          - aws_access_key_id
          - aws_secret_access_key
      bucket: aleign-chat
      region: ap-southeast-2
      source: /drone/build
      target: /${DRONE_REPO_BRANCH}
      delete: true
      when:
          event: push
          branch:
            - staging
            - master
