checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"

supportedArchitectures:
  cpu:
    - arm64
    - x64
  libc:
    - glibc
    - musl
  os:
    - linux

yarnPath: .yarn/releases/yarn-4.11.0.cjs
