checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

nodeLinker: node-modules

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32

  cpu:
    - current
    - x64
    - ia32
    - arm64

  libc:
    - current
    - glibc
    - musl

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'

yarnPath: .yarn/releases/yarn-4.9.3.cjs
