services:
  presence-service:
    build:
      target: release-fips
    image: ghcr.io/${LOWERCASE_REPOSITORY}/presence-service:${DOCKER_TAG}-fips

  ddp-streamer-service:
    build:
      target: release-fips
    image: ghcr.io/${LOWERCASE_REPOSITORY}/ddp-streamer-service:${DOCKER_TAG}-fips
