name: 'Meteor Build'

inputs:
  type:
    required: false
    description: 'production or coverage'
    default: 'production'
  reset-meteor:
    required: false
    description: 'Reset Meteor'
    type: boolean
  node-version:
    required: true
    description: 'Node version'
    type: string
  NPM_TOKEN:
    required: false
    description: 'NPM token'
  deno-version:
    required: true
    description: 'Deno version'
    type: string
  source-hash:
    required: true
    description: 'Source code hash'
    type: string

runs:
  using: composite

  steps:
    - name: Cache build
      uses: actions/cache@v4
      id: cache-build
      with:
        path: /tmp/Rocket.Chat.tar.gz
        key: ${{ runner.os }}-${{ runner.arch }}-${{ inputs.type }}-rc-build-${{ inputs.source-hash }}

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      if: steps.cache-build.outputs.cache-hit != 'true'
      with:
        swap-size-gb: 4

    - name: Setup NodeJS
      uses: ./.github/actions/setup-node
      if: steps.cache-build.outputs.cache-hit != 'true'
      with:
        node-version: ${{ inputs.node-version }}
        deno-version: ${{ inputs.deno-version }}
        cache-modules: true
        install: true
        type: 'production'
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}

    # - name: Free disk space
    #   run: |
    #     sudo apt clean
    #     docker rmi $(docker image ls -aq)
    #     df -h

    - name: Cache vite
      uses: actions/cache@v3
      if: steps.cache-build.outputs.cache-hit != 'true'
      with:
        path: ./node_modules/.vite
        key: vite-local-cache-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package.json') }}
        restore-keys: |
          vite-local-cache-${{ runner.os }}-${{ runner.arch }}-

    - name: Cache meteor local
      uses: actions/cache@v3
      if: steps.cache-build.outputs.cache-hit != 'true'
      with:
        path: ./apps/meteor/.meteor/local
        key: meteor-local-cache-${{ runner.os }}-${{ runner.arch }}-${{ inputs.type }}-${{ hashFiles('apps/meteor/.meteor/versions') }}
        restore-keys: |
          meteor-local-cache-${{ runner.os }}-${{ runner.arch }}-${{ inputs.type }}-

    - name: Cache meteor
      uses: actions/cache@v3
      if: steps.cache-build.outputs.cache-hit != 'true'
      with:
        path: ~/.meteor
        key: meteor-cache-${{ runner.os }}-${{ runner.arch }}-${{ inputs.type }}-${{ hashFiles('apps/meteor/.meteor/release') }}
        restore-keys: |
          meteor-cache-${{ runner.os }}-${{ runner.arch }}-${{ inputs.type }}-

    - name: Install Meteor
      shell: bash
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: |
        # Restore bin from cache
        set +e
        METEOR_SYMLINK_TARGET=$(readlink ~/.meteor/meteor)
        METEOR_TOOL_DIRECTORY=$(dirname "$METEOR_SYMLINK_TARGET")
        set -e
        LAUNCHER=$HOME/.meteor/$METEOR_TOOL_DIRECTORY/scripts/admin/launch-meteor
        if [ -e $LAUNCHER ]
        then
          echo "Cached Meteor bin found, restoring it"
          sudo cp "$LAUNCHER" "/usr/local/bin/meteor"
        else
          echo "No cached Meteor bin found."
        fi

        # only install meteor if bin isn't found
        command -v meteor >/dev/null 2>&1 || curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh

    - name: Versions
      shell: bash
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: |
        npm --versions
        yarn -v
        node -v
        meteor --version
        meteor npm --versions
        meteor node -v
        git version

    - uses: rharkor/caching-for-turbo@v1.8

    - name: Reset Meteor
      shell: bash
      if: ${{ steps.cache-build.outputs.cache-hit != 'true' && inputs.reset-meteor == 'true' }}
      working-directory: ./apps/meteor
      run: meteor reset

    - name: Restore packages build
      uses: actions/download-artifact@v6
      with:
        name: packages-build
        path: /tmp

    - name: Unpack packages build
      shell: bash
      run: |
        tar -xzf /tmp/RocketChat-packages-build.tar.gz -C .

    - name: Build Rocket.Chat
      shell: bash
      if: steps.cache-build.outputs.cache-hit != 'true'
      env:
        METEOR_PROFILE: 1000
        BABEL_ENV: ${{ inputs.type }}
      run: |
        # check if BABEL_ENV is set to coverage
        if [[ $BABEL_ENV == "coverage" ]]; then
          echo -e "rocketchat:coverage\n" >> ./apps/meteor/.meteor/packages
          echo "Coverage enabled"
        fi

        yarn build:ci

    - name: Prepare build
      shell: bash
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: |
        cd /tmp/dist
        tar czf /tmp/Rocket.Chat.tar.gz bundle

    - name: Store build
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ inputs.type }}
        path: /tmp/Rocket.Chat.tar.gz
        overwrite: true
        include-hidden-files: true
