export default {
	all: {
		'mocha/handle-done-callback': 'error',
		'mocha/max-top-level-suites': 'error',
		'mocha/no-async-suite': 'error',
		'mocha/no-exclusive-tests': 'error',
		'mocha/no-exports': 'error',
		'mocha/no-global-tests': 'error',
		'mocha/no-hooks': 'error',
		'mocha/no-hooks-for-single-case': 'error',
		'mocha/no-identical-title': 'error',
		'mocha/no-mocha-arrows': 'error',
		'mocha/no-nested-tests': 'error',
		'mocha/no-pending-tests': 'error',
		'mocha/no-return-and-callback': 'error',
		'mocha/no-return-from-async': 'error',
		'mocha/no-setup-in-describe': 'error',
		'mocha/no-sibling-hooks': 'error',
		'mocha/no-synchronous-tests': 'error',
		'mocha/no-top-level-hooks': 'error',
		'mocha/prefer-arrow-callback': 'error',
		'mocha/consistent-spacing-between-blocks': 'error',
		'mocha/consistent-interface': ['error', { interface: 'BDD' }],
		'mocha/valid-suite-title': 'error',
		'mocha/valid-test-title': 'error',
		'mocha/no-empty-title': 'error',
	},
	recommended: {
		'mocha/handle-done-callback': 'error',
		'mocha/max-top-level-suites': ['error', { limit: 1 }],
		'mocha/no-async-suite': 'error',
		'mocha/no-exclusive-tests': 'warn',
		'mocha/no-exports': 'error',
		'mocha/no-global-tests': 'error',
		'mocha/no-hooks': 'off',
		'mocha/no-hooks-for-single-case': 'off',
		'mocha/no-identical-title': 'error',
		'mocha/no-mocha-arrows': 'error',
		'mocha/no-nested-tests': 'error',
		'mocha/no-pending-tests': 'warn',
		'mocha/no-return-and-callback': 'error',
		'mocha/no-return-from-async': 'off',
		'mocha/no-setup-in-describe': 'error',
		'mocha/no-sibling-hooks': 'error',
		'mocha/no-synchronous-tests': 'off',
		'mocha/no-top-level-hooks': 'warn',
		'mocha/prefer-arrow-callback': 'off',
		'mocha/valid-suite-title': 'off',
		'mocha/valid-test-title': 'off',
		'mocha/no-empty-title': 'error',
		'mocha/consistent-spacing-between-blocks': 'error',
	},
} as const;
