import { Meteor } from 'meteor/meteor';

import { settingsRegistry } from '../../settings/server';

Meteor.startup(function () {
	const enableQuery = {
		_id: 'Katex_Enabled',
		value: true,
	};
	settingsRegistry.add('Katex_Enabled', true, {
		type: 'boolean',
		group: 'Message',
		section: 'Katex',
		public: true,
		i18nDescription: 'Katex_Enabled_Description',
	});
	settingsRegistry.add('Katex_Parenthesis_Syntax', true, {
		type: 'boolean',
		group: 'Message',
		section: 'Katex',
		public: true,
		enableQuery,
		i18nDescription: 'Katex_Parenthesis_Syntax_Description',
	});
	return settingsRegistry.add('Katex_Dollar_Syntax', false, {
		type: 'boolean',
		group: 'Message',
		section: 'Katex',
		public: true,
		enableQuery,
		i18nDescription: 'Katex_Dollar_Syntax_Description',
	});
});

// ---
// generated by coffee-script 1.9.2
