export enum OtrRoomState {
	DISABLED = 'DISABLED',
	NOT_STARTED = 'NOT_STARTED',
	ESTABLISHING = 'ESTABLISHING',
	ESTABLISHED = 'ESTABLISHED',
	ERROR = 'ERROR',
	TIMEOUT = 'TIMEOUT',
	DECLINED = 'DECLINED',
}
