/**
 * @file test-rspack.js
 * @description Bundled output generated by Rspack for tests
 * --------------------------------------------------------------------------
 * ⚡ Rspack Test App (Test)
 * --------------------------------------------------------------------------
 * • [   test-entry.js ] ──▶ [■ test-rspack.js ] ──▶ [   test-meteor.js ]
 *
 * This file is the bundle that Rspack outputs for tests. It contains all of
 * your test code in one optimized file. Next step is loading this bundle via
 * `test-meteor.js`.
 *
 * ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
 * These files also act as a cache: they can be safely removed and will be
 * regenerated on the next build. They should be ignored in IDE suggestions
 * and version control.
 */

/* Code generated */
