/**
 * @file test-meteor.js
 * @description Meteor runtime file that imports the Rspack test bundle
 * --------------------------------------------------------------------------
 * ☄️ Meteor Test App (Test)
 * --------------------------------------------------------------------------
 * • [   test-entry.js ] ──▶ [   test-rspack.js ] ──▶ [■ test-meteor.js ]
 *
 * Defined under `meteor.testModule` in package.json. Meteor loads this
 * file at runtime to import the Rspack test bundle (`test-rspack.js`) and
 * run your tests.
 *
 * ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
 * These files also act as a cache: they can be safely removed and will be
 * regenerated on the next build. They should be ignored in IDE suggestions
 * and version control.
 */

/* Link to ⚡ Rspack Test App */
import './client-rspack.js';
