/**
 * @file test-entry.js
 * @description Entry point for Rspack test build process
 * --------------------------------------------------------------------------
 * ⚡ Rspack Test Entry (Test)
 * --------------------------------------------------------------------------
 * • [■ test-entry.js ] ──▶ [   test-rspack.js ] ──▶ [   test-meteor.js ]
 *
 * This file is the starting point for the Rspack test build. It imports your
 * Meteor app's test modules so Rspack can resolve every dependency and
 * generate the bundled output: `test-rspack.js`.
 *
 * ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
 * These files also act as a cache: they can be safely removed and will be
 * regenerated on the next build. They should be ignored in IDE suggestions
 * and version control.
 */

/* Tests automatically imported */
