export enum E2EEState {
	NOT_STARTED = 'NOT_STARTED',
	DISABLED = 'DISABLED',
    LOADING_KEYS = 'LOADING_KEYS',
	READY = 'READY',
    SAVE_PASSWORD = 'SAVE_PASSWORD',
    ENTER_PASSWORD = 'ENTER_PASSWORD',
	ERROR = 'ERROR',
};
