import './oauth/stylesheets/oauth2.css';
import './oauth/oauth2-client.html';
import './oauth/oauth2-client';
import './admin/startup';
import './admin/route';
import './admin/views/oauthApp.html';
import './admin/views/oauthApp';
import './admin/views/oauthApps.html';
import './admin/views/oauthApps';
