export { Apps } from './orchestrator';
import './admin/apps.html';
import './admin/apps';
import './admin/appInstall.html';
import './admin/appInstall';
import './admin/appLogs.html';
import './admin/appLogs';
import './admin/appManage.html';
import './admin/appManage';
import './admin/appWhatIsIt.html';
import './admin/appWhatIsIt';
