/**
 * @file client-rspack.js
 * @description Bundled output generated by Rspack
 * --------------------------------------------------------------------------
 * ⚡ Rspack Client App (Production)
 * --------------------------------------------------------------------------
 * • [   client-entry.js ] ──▶ [■ client-rspack.js ] ──▶ [   client-meteor.js ]
 *
 * This file is the bundled output generated by Rspack.
 * It contains all application code and assets combined into one build.
 * It is not used directly, but will be imported by the Meteor main module
 * file (`client-meteor.js`) so that Meteor runs the Rspack bundle.
 *
 * ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
 * These files also act as a cache: they can be safely removed and will be
 * regenerated on the next build. They should be ignored in IDE suggestions
 * and version control.
 */

/* Link to ⚡ Rspack Client App */
import './client-rspack.js';
