/**
 * @file server-meteor.js
 * @description Meteor runtime file that imports the Rspack bundle
 * --------------------------------------------------------------------------
 * ☄️ Meteor Server App (Production)
 * --------------------------------------------------------------------------
 * • [   server-entry.js ] ──▶ [   server-rspack.js ] ──▶ [■ server-meteor.js ]
 *
 * This file overrides the corresponding `meteor.mainModule.server` entry in
 * package.json. Meteor loads it at runtime, and it imports the Rspack
 * bundle (`server-rspack.js`) so the application executes using the build
 * produced by Rspack.
 *
 * ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
 * These files also act as a cache: they can be safely removed and will be
 * regenerated on the next build. They should be ignored in IDE suggestions
 * and version control.
 */

/* Link to ⚡ Rspack Server App */
import './server-rspack.js';
