RocketChat.theme.addColor "content-background-color", "#FFF"
RocketChat.theme.addColor "primary-background-color", "#04436A"
RocketChat.theme.addColor "secondary-background-color", "#F4F4F4"
RocketChat.theme.addColor "tertiary-background-color", "#EAEAEA"
RocketChat.theme.addColor "primary-font-color", "#444444"
RocketChat.theme.addColor "secondary-font-color", "#7F7F7F"
RocketChat.theme.addColor "tertiary-font-color", "rgba(255, 255, 255, 0.6)"
RocketChat.theme.addColor "input-font-color", "rgba(255, 255, 255, 0.85)"
RocketChat.theme.addColor "link-font-color", "#008CE3"
RocketChat.theme.addColor "info-font-color", "#AAAAAA"
RocketChat.theme.addColor "info-active-font-color", "#FF0000"
RocketChat.theme.addColor "smallprint-font-color", "#C2E7FF"
RocketChat.theme.addColor "smallprint-hover-color", "white"
RocketChat.theme.addColor "status-online", "#35AC19"
RocketChat.theme.addColor "status-offline", "rgba(150, 150, 150, 0.50)"
RocketChat.theme.addColor "status-busy", "#D30230"
RocketChat.theme.addColor "status-away", "#FCB316"
RocketChat.theme.addColor "code-background", "#F8F8F8"
RocketChat.theme.addColor "code-border", "#CCC"
RocketChat.theme.addColor "code-color", "#333"
RocketChat.theme.addColor "blockquote-background", "#CCC"

RocketChat.theme.compile()
