/* eslint-disable */

// before using this script make sure to run: npm i --no-save node-sprite-generator

// node --experimental-modules generateEmojiIndex.mjs
import fs from 'fs';
import nsg from 'node-sprite-generator';
import _ from 'underscore';
import path from 'path';

// helper to resolve paths relative to this script file
const scriptDir = path.dirname(new URL(import.meta.url).pathname);

// Node 18+ has global fetch; if not available uncomment next line
// import fetch from 'node-fetch';

// Resolve the path to emoji-json using Node's module resolution so the
// script can be run from any working directory. Using createRequire avoids
// experimental JSON import assertions and works reliably in ESM.
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const emojiJsonFile = require.resolve('emoji-toolkit/emoji.json');

// directory where we'll temporarily store downloaded PNGs when using CDN
// keep cache scoped to the script directory so that generated files don't
// clutter the workspace root when the script is invoked from elsewhere.
const tmpFolder = path.join(scriptDir, '.emoji-cache');

// ensure cache directory exists (for CDN downloads)
fs.mkdirSync(tmpFolder, { recursive: true });

const emojiJson = fs.readFileSync(emojiJsonFile, 'utf8');

generateEmojiPicker(emojiJson);


async function generateEmojiPicker(data) {
    const emojiList = JSON.parse(data);
    console.log(`${Object.keys(emojiList).length} emojis found.`);

    let toneList = [];
    let emojisByCategory = {};

    // iterate in order field to keep categories sorted
    _.sortBy(Object.entries(emojiList), (a) => a[1].order).forEach(([code, emoji]) => {
        if (emoji && emoji.shortname) {
            const toneIndex = emoji.shortname.indexOf('_tone');
            if (toneIndex !== -1) {
                const tone = emoji.shortname.replace(/:/g, '').split('_tone')[0];
				if (!toneList.includes(tone)) {
					toneList.push(tone);
				}
				return;
			}
		}

		if (!emojisByCategory[emoji.category]) {
			emojisByCategory[emoji.category] = [];
		}
		emojisByCategory[emoji.category].push(code);
	});

	let output = `/*
 * This file is automatically generated from generateEmojiIndex.mjs
 * Last generated ${Date().toString()}
 *
 * Mapping category hashes into human readable and translated names
 */\n\n`;

	const emojiCategoriesMapping = [
		{ key: 'people', i18n: 'Smileys_and_People' },
		{ key: 'nature', i18n: 'Animals_and_Nature' },
		{ key: 'food', i18n: 'Food_and_Drink' },
		{ key: 'activity', i18n: 'Activity' },
		{ key: 'travel', i18n: 'Travel_and_Places' },
		{ key: 'objects', i18n: 'Objects' },
		{ key: 'symbols', i18n: 'Symbols' },
		{ key: 'flags', i18n: 'Flags' },
	];

	// emojiCategories
	output += `export const emojiCategories = [\n`;
	for (let category in emojisByCategory) {
		const map = emojiCategoriesMapping.find((o) => o.key === category);
		if (map) {
			output += `\t{ key: '${category}', i18n: '${map.i18n}' },\n`;
		} else {
			if (category !== 'modifier' || category !== 'regional') {
				console.error(`No emojiCategory mapping for ${category}`);
			}
		}
	}
	output += `];\n`;

	// toneList
	const needsQuotes = ['-'];
	output += `export const toneList = {\n`;
	for (let tone in toneList) {
		if (toneList[tone].includes(needsQuotes)) {
			output += `\t'${toneList[tone]}': 1,\n`;
		} else {
			output += `\t${toneList[tone]}: 1,\n`;
		}
	}
	output += `};\n`;

	// emojisByCategory
	output += `export const emojisByCategory = {\n`;
	for (const category of Object.keys(emojisByCategory)) {
		output += `\t${category}: [\n`;

		for (const code of emojisByCategory[category]) {
			const short = emojiList[code].shortname.replace(/:/g, '');
			output += `\t\t'${short}',\n`;
		}

		output += `\t],\n`;
	}
	output += `};\n`;

	fs.writeFileSync('emojiPicker.js', output, {
		encoding: 'utf8',
		flag: 'w',
	});
	console.log('Generated emojiPicker.js!');

	console.log('Generating sprite sheets....');

	let spriteCss = '';

	for (let category in emojisByCategory) {
		let srcList = [];
		let diversityList = {};
		const emojis = _.filter(emojiList, (x) => x.category === category);
		// derive output paths relative to this script, not the cwd
		const spritePath = path.resolve(scriptDir, '../../../public/packages/emojione', `${category}-sprites.png`);
		const cssOutputPath = path.resolve(scriptDir, '../client', `${category}-sprites.css`);

		for (const emoji of emojis) {
			const code = emoji.code_points.base;
			const localPath = `${tmpFolder}/${code}.png`;
			if (!fs.existsSync(localPath)) {
				const url = `https://cdn.jsdelivr.net/npm/emoji-toolkit@latest/assets/64/${code}.png`;
				console.log(`fetching ${url}`);
				const res = await fetch(url);
				if (res.ok) {
					const buf = await res.arrayBuffer();
					fs.writeFileSync(localPath, Buffer.from(buf));
				} else {
					console.warn(`failed to download ${code} (${res.status})`);
				}
			}
			srcList.push(localPath);
			if (emoji.diversity) {
				diversityList[code] = true;
			}
		}
		spriteCss += `@import './${category}-sprites.css';\n`;

		// filter out any images that failed to download
		srcList = srcList.filter((p) => fs.existsSync(p));
		const templateFile = path.join(scriptDir, 'emojione.tpl');

		nsg(
			{
				src: srcList,
				spritePath: spritePath,
				layout: 'packed',
				stylesheet: templateFile,
				stylesheetPath: cssOutputPath,
				compositor: 'gm',
				layoutOptions: {
					scaling: 1,
				},
				stylesheetOptions: {
					prefix: '',
					diversityList: diversityList,
					category: category,
					spritePath: `/packages/emojione/${category}-sprites.png`,
					pixelRatio: 1,
				},
			},
			function (err) {
				if (err) {
					console.error(err);
					return;
				}
				console.log(`${category}'s sprite generated!`);
			},
		);
	}

	spriteCss += `
.emojione {
	position: relative;

	display: inline-block;
	overflow: hidden;

	width: 1.375rem;
	height: 1.375rem;
	margin: 0 0.15em;

	vertical-align: middle;
	white-space: nowrap;
	text-indent: 100%;

	font-size: inherit;
	line-height: normal;
	image-rendering: -webkit-optimize-contrast;
	image-rendering: optimizeQuality;
}
`;
	const emojioneCssPath = path.resolve(scriptDir, '../client/emojione-sprites.css');
	fs.writeFileSync(emojioneCssPath, spriteCss, {
		encoding: 'utf8',
		flag: 'w',
	});
}
