import './startup/settings';
import './methods/callWith2fa';
import './methods/sendEmailCode';
import './methods/checkCodesRemaining';
import './methods/disable';
import './methods/enable';
import './methods/regenerateCodes';
import './methods/validateTempToken';
import './loginHandler';
