name: Changeset release
description: Action to cut and publish releases using changesets

inputs:
  action:
    description: "The main action to perform: publish, publish-final, bump or patch"
    required: true
  base-ref:
    description: "Base ref to use for the release"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "package"
  color: "blue"
