name: Changeset release
description: Action to cut and publish releases using changesets

inputs:
  action:
    description: "The main action to perform: publish-final, cut, next, patch, update-pr-description or"
    required: true
  base-ref:
    description: "Base ref to use for the release"
    required: false
  release-tag:
    description: "Release tag to use for the update-release action"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "package"
  color: "blue"
