name: Update Version Durability
description: Update Version Durability page on Document360

inputs:
  LTS_VERSIONS:
    required: true
    description: Comma separated list of LTS versions
  GH_TOKEN:
    required: true
    description: GitHub API Token
  D360_TOKEN:
    required: true
    description: Document360 API Token
  D360_ARTICLE_ID:
    required: true
    description: Document360 Article ID
  PUBLISH:
    required: true
    description: Publish Draft

runs:
  using: node20
  main: index.js
