name: 'Docker Image Size Tracker'
description: 'Track and report Docker image sizes in Pull Requests'
author: 'Rocket.Chat'

inputs:
  github-token:
    description: 'GitHub token for commenting on PRs'
    required: true
  registry:
    description: 'Container registry (e.g., ghcr.io)'
    required: false
    default: 'ghcr.io'
  repository:
    description: 'Repository name (e.g., rocketchat)'
    required: true
  tag:
    description: 'Image tag to measure'
    required: true
  baseline-tag:
    description: 'Baseline tag to compare against'
    required: false
    default: 'develop'
  services:
    description: 'JSON array of service names to track'
    required: false
    default: '["rocketchat","authorization-service","account-service","ddp-streamer-service","presence-service","stream-hub-service","queue-worker-service","omnichannel-transcript-service"]'

outputs:
  total-size:
    description: 'Total size in bytes'
    value: ${{ steps.measure.outputs.total-size }}
  size-diff:
    description: 'Size difference in bytes'
    value: ${{ steps.compare.outputs.size-diff }}
  size-diff-percent:
    description: 'Size difference percentage'
    value: ${{ steps.compare.outputs.size-diff-percent }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      shell: bash
      run: |
        if ! command -v skopeo &> /dev/null; then
          sudo apt-get update -qq
          sudo apt-get install -y skopeo jq bc
        fi

    - name: Measure image sizes
      id: measure
      shell: bash
      run: |
        set -o xtrace

        SERVICES='${{ inputs.services }}'
        REGISTRY="${{ inputs.registry }}"
        ORG="${{ inputs.repository }}"
        TAG="${{ inputs.tag }}"

        echo "Measuring images: $REGISTRY/$ORG/*:$TAG"

        declare -A sizes
        total=0

        for service in $(echo "$SERVICES" | jq -r '.[]'); do
          if [[ "$service" == "rocketchat" ]]; then
            image_name="rocket.chat"
          else
            image_name="$service"
          fi

          image="$REGISTRY/$ORG/$image_name:$TAG"
          image_not_tag="$REGISTRY/$ORG/$image_name"
          echo "Measuring $image..."

          size=0
          if manifest=$(skopeo inspect --raw "docker://$image" 2>/dev/null); then
            # Handle multi-arch manifests
            if echo "$manifest" | jq -e '.manifests' > /dev/null 2>&1; then
              digest=$(echo "$manifest" | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest' | head -1)
              if [[ -n "$digest" ]]; then
                manifest=$(skopeo inspect --raw "docker://$image_not_tag@$digest" 2>/dev/null)
              fi
            fi

            # Sum layer sizes
            size=$(echo "$manifest" | jq '[.layers[]?.size // 0] | add // 0')
            config_size=$(echo "$manifest" | jq '.config.size // 0')
            size=$((size + config_size))
          fi

          echo "  → $service: $size bytes"
          sizes[$service]=$size
          total=$((total + size))
        done

        echo "total-size=$total" >> $GITHUB_OUTPUT

        # Save to JSON
        echo "{" > current-sizes.json
        echo "  \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"," >> current-sizes.json
        echo "  \"tag\": \"$TAG\"," >> current-sizes.json
        echo "  \"total\": $total," >> current-sizes.json
        echo "  \"services\": {" >> current-sizes.json

        first=true
        for service in $(echo "$SERVICES" | jq -r '.[]'); do
          if [[ "$first" == "true" ]]; then
            first=false
          else
            echo "," >> current-sizes.json
          fi
          echo "    \"$service\": ${sizes[$service]}" >> current-sizes.json
        done

        echo "  }" >> current-sizes.json
        echo "}" >> current-sizes.json

    - name: Measure baseline
      id: baseline
      shell: bash
      continue-on-error: true
      run: |
        SERVICES='${{ inputs.services }}'
        REGISTRY="${{ inputs.registry }}"
        ORG="${{ inputs.repository }}"
        TAG="${{ inputs.baseline-tag }}"

        echo "Measuring baseline: $REGISTRY/$ORG/*:$TAG"

        declare -A sizes
        total=0

        for service in $(echo "$SERVICES" | jq -r '.[]'); do
          if [[ "$service" == "rocketchat" ]]; then
            image_name="rocket.chat"
          else
            image_name="$service"
          fi

          image="$REGISTRY/$ORG/$image_name:$TAG"
          image_not_tag="$REGISTRY/$ORG/$image_name"

          size=0
          if manifest=$(skopeo inspect --raw "docker://$image" 2>/dev/null); then
            if echo "$manifest" | jq -e '.manifests' > /dev/null 2>&1; then
              digest=$(echo "$manifest" | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest' | head -1)
              if [[ -n "$digest" ]]; then
                manifest=$(skopeo inspect --raw "docker://$image_not_tag@$digest" 2>/dev/null)
              fi
            fi

            size=$(echo "$manifest" | jq '[.layers[]?.size // 0] | add // 0')
            config_size=$(echo "$manifest" | jq '.config.size // 0')
            size=$((size + config_size))
          fi

          sizes[$service]=$size
          total=$((total + size))
        done

        echo "baseline-total=$total" >> $GITHUB_OUTPUT

        echo "{" > baseline-sizes.json
        echo "  \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"," >> baseline-sizes.json
        echo "  \"tag\": \"$TAG\"," >> baseline-sizes.json
        echo "  \"total\": $total," >> baseline-sizes.json
        echo "  \"services\": {" >> baseline-sizes.json

        first=true
        for service in $(echo "$SERVICES" | jq -r '.[]'); do
          if [[ "$first" == "true" ]]; then
            first=false
          else
            echo "," >> baseline-sizes.json
          fi
          echo "    \"$service\": ${sizes[$service]}" >> baseline-sizes.json
        done

        echo "  }" >> baseline-sizes.json
        echo "}" >> baseline-sizes.json

    - name: Setup history storage
      id: history
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Try to fetch history branch
        if git ls-remote --heads origin image-size-history | grep -q image-size-history; then
          git fetch origin image-size-history:image-size-history
          git checkout image-size-history
        else
          # Create orphan branch for history
          git checkout --orphan image-size-history
          git rm -rf . 2>/dev/null || true
          mkdir -p history
          echo "# Image Size History" > README.md
          echo "This branch stores historical image size data for tracking" >> README.md
          git add README.md
          git commit -m "Initialize image size history"
        fi

        mkdir -p history

    - name: Load historical data
      id: load-history
      shell: bash
      run: |
        # Load last 30 measurements
        echo "[]" > history-data.json
        if [[ -d history ]]; then
          jq -s '.' history/*.json 2>/dev/null | jq 'sort_by(.timestamp) | .[-30:]' > history-data.json || echo "[]" > history-data.json
        fi

        count=$(jq 'length' history-data.json)
        echo "Loaded $count historical measurements"

    - name: Save current measurement to history
      if: github.ref == 'refs/heads/develop'
      shell: bash
      run: |
        timestamp=$(date -u +%Y%m%d-%H%M%S)
        commit_sha="${{ github.sha }}"

        # Add commit info to current measurement
        jq --arg sha "$commit_sha" '. + {commit: $sha}' current-sizes.json > "history/${timestamp}.json"

        git add "history/${timestamp}.json"
        git commit -m "Add measurement for ${timestamp} (${commit_sha:0:7})"
        git push origin image-size-history

        echo "Saved measurement to history"

    - name: Compare and generate report
      id: compare
      shell: bash
      run: |
        current_total=$(jq -r '.total' current-sizes.json)

        if [[ ! -f baseline-sizes.json ]]; then
          echo "No baseline available"
          echo "size-diff=0" >> $GITHUB_OUTPUT
          echo "size-diff-percent=0" >> $GITHUB_OUTPUT

          cat > report.md << 'EOF'
        # 📦 Docker Image Size Report

        **Status:** First measurement - no baseline for comparison

        **Total Size:** $(numfmt --to=iec-i --suffix=B $current_total)
        EOF
          exit 0
        fi

        baseline_total=$(jq -r '.total' baseline-sizes.json)
        diff=$((current_total - baseline_total))

        if [[ $baseline_total -gt 0 ]]; then
          percent=$(awk "BEGIN {printf \"%.2f\", ($diff / $baseline_total) * 100}")
        else
          percent=0
        fi

        echo "size-diff=$diff" >> $GITHUB_OUTPUT
        echo "size-diff-percent=$percent" >> $GITHUB_OUTPUT

        # Generate report
        if (( $(echo "$diff > 0" | bc -l) )); then
          emoji="📈"
          badge="![](https://img.shields.io/badge/size-+${percent}%25-red)"
          sign="+"
        elif (( $(echo "$diff < 0" | bc -l) )); then
          emoji="📉"
          badge="![](https://img.shields.io/badge/size-${percent}%25-green)"
          sign=""
        else
          emoji="➡️"
          badge="![](https://img.shields.io/badge/size-unchanged-gray)"
          sign=""
        fi

        cat > report.md << EOF
        # 📦 Docker Image Size Report

        ## $emoji Summary $badge

        | Metric | Value |
        |--------|-------|
        | **Current Total** | $(numfmt --to=iec-i --suffix=B $current_total) |
        | **Baseline Total** | $(numfmt --to=iec-i --suffix=B $baseline_total) |
        | **Difference** | **${sign}$(numfmt --to=iec-i --suffix=B ${diff#-})** (${sign}${percent}%) |

        ## 📊 Service Details

        | Service | Current | Baseline | Change |
        |---------|---------|----------|--------|
        EOF

        SERVICES='${{ inputs.services }}'
        for service in $(echo "$SERVICES" | jq -r '.[]'); do
          current=$(jq -r ".services.\"$service\"" current-sizes.json)
          baseline=$(jq -r ".services.\"$service\"" baseline-sizes.json)
          service_diff=$((current - baseline))

          if [[ $service_diff -gt 0 ]]; then
            icon="📈"
            sign="+"
          elif [[ $service_diff -lt 0 ]]; then
            icon="📉"
            sign=""
          else
            icon="➡️"
            sign=""
          fi

          echo "| $icon **$service** | $(numfmt --to=iec-i --suffix=B $current) | $(numfmt --to=iec-i --suffix=B $baseline) | ${sign}$(numfmt --to=iec-i --suffix=B ${service_diff#-}) |" >> report.md
        done

        # Generate historical trend chart
        echo "" >> report.md
        echo "## 📈 Historical Trend" >> report.md
        echo "" >> report.md

        # Load history and generate mermaid chart
        history_count=$(jq 'length' history-data.json)

        if [[ $history_count -gt 0 ]]; then
          # Generate Mermaid chart data
          x_labels=""
          y_values=""

          while IFS= read -r line; do
            timestamp=$(echo "$line" | jq -r '.timestamp')
            total=$(echo "$line" | jq -r '.total')

            date_label=$(echo "$timestamp" | cut -d'T' -f1 | cut -d'-' -f2- | tr '-' '/')
            size_gb=$(awk "BEGIN {printf \"%.2f\", $total / 1073741824}")

            if [[ -z "$x_labels" ]]; then
              x_labels="\"$date_label\""
              y_values="$size_gb"
            else
              x_labels="$x_labels, \"$date_label\""
              y_values="$y_values, $size_gb"
            fi
          done < <(jq -c '.[]' history-data.json)

          # Add current PR as last point
          current_date=$(date -u +"%m/%d")
          current_gb=$(awk "BEGIN {printf \"%.2f\", $current_total / 1073741824}")
          x_labels="$x_labels, \"$current_date (PR)\""
          y_values="$y_values, $current_gb"

          cat >> report.md << EOF
        \`\`\`mermaid
        %%{init: {'theme':'base'}}%%
        xychart-beta
          title "Total Image Size Evolution (Last 30 Builds + This PR)"
          x-axis [$x_labels]
          y-axis "Size (GB)" 0 --> 20
          line [$y_values]
        \`\`\`

        EOF

          # Add summary stats
          min_size=$(jq '[.[].total] | min' history-data.json)
          max_size=$(jq '[.[].total] | max' history-data.json)
          avg_size=$(jq '[.[].total] | add / length' history-data.json)

          cat >> report.md << EOF
        **Statistics (last $history_count builds):**
        - 📊 Average: $(numfmt --to=iec-i --suffix=B ${avg_size%.*})
        - ⬇️ Minimum: $(numfmt --to=iec-i --suffix=B $min_size)
        - ⬆️ Maximum: $(numfmt --to=iec-i --suffix=B $max_size)
        - 🎯 Current PR: $(numfmt --to=iec-i --suffix=B $current_total)

        EOF

        else
          cat >> report.md << 'EOF'
        *No historical data available yet. History tracking starts after merging to develop.*

        EOF
        fi

        cat >> report.md << EOF

        <details>
        <summary>ℹ️ About this report</summary>

        This report compares Docker image sizes from this build against the \`${{ inputs.baseline-tag }}\` baseline.

        - **Tag:** \`${{ inputs.tag }}\`
        - **Baseline:** \`${{ inputs.baseline-tag }}\`
        - **Timestamp:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
        - **Historical data points:** $history_count

        </details>
        EOF

    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');

          if (!fs.existsSync('report.md')) {
            console.log('No report found, skipping comment');
            return;
          }

          const report = fs.readFileSync('report.md', 'utf8');

          // Find existing comment
          const comments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });

          const botComment = comments.data.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('📦 Docker Image Size Report')
          );

          const commentBody = report + '\n\n---\n*Updated: ' + new Date().toUTCString() + '*';

          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: commentBody
            });
            console.log('Updated existing comment');
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });
            console.log('Created new comment');
          }

branding:
  icon: 'package'
  color: 'blue'
