#!/usr/bin/env bash
#
# Sourced, not executed. Builds docker-compose.overrides.yml — the one generated
# compose file devcontainer.json includes alongside docker-compose.yml.
#
# Why anything is generated: compose files are static and devcontainer.json's
# `dockerComposeFile` list cannot be computed, yet two things about this
# container are only knowable on the host at initializeCommand time — whether
# the checkout is a linked git worktree, and which features devcontainer.json
# declares. Everything a feature owns (its shared volume, where that volume
# mounts, any capability it needs) therefore has to be injected rather than
# checked in, or commenting the feature out would still leave compose demanding
# its external volume and failing the create outright.
#
# Contributors never write the file. Each appends a fragment to a staging
# directory under one of three buckets, and initialize.sh merges them once at
# the end:
#
#   service          arbitrary keys under services.app (cap_add, environment, ...)
#   service-volumes  list items for services.app.volumes
#   volumes          entries for the top-level volumes map
#
# Buckets exist because YAML has no merge: two fragments both opening `volumes:`
# under the same node would be a duplicate key, which compose rejects. Within a
# bucket, merging is concatenation at a fixed indent — so a fragment is authored
# unindented and reads fine on its own.
#
# The staging directory is passed to child scripts through the environment
# (RC_COMPOSE_OVERRIDES_DIR) because they run as separate `bash` processes, not
# as sourced functions.

_overrides_out="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/docker-compose.overrides.yml"

# Buckets in emit order. `service` before `service-volumes` only so the
# generated file reads with the volume list last, like a hand-written one.
_overrides_buckets=(service service-volumes volumes)

_overrides_dir() {
	if [ -z "${RC_COMPOSE_OVERRIDES_DIR:-}" ]; then
		printf '\033[1;31m[overrides]\033[0m RC_COMPOSE_OVERRIDES_DIR is unset — this runs from scripts/initialize.sh\n' >&2
		return 1
	fi
	printf '%s\n' "$RC_COMPOSE_OVERRIDES_DIR"
}

# overrides_reset — creates the staging directory and exports its path.
# Called once, by initialize.sh, before any contributor runs.
overrides_reset() {
	RC_COMPOSE_OVERRIDES_DIR="$(mktemp -d)"
	export RC_COMPOSE_OVERRIDES_DIR
}

# overrides_cleanup — removes the staging directory. Safe to call twice.
overrides_cleanup() {
	[ -n "${RC_COMPOSE_OVERRIDES_DIR:-}" ] || return 0
	rm -rf "$RC_COMPOSE_OVERRIDES_DIR"
}

# overrides_add <contributor> <bucket> — fragment body on stdin.
#
# One file per contributor per bucket, so a contributor that runs twice (the
# hooks are all idempotent) replaces its own fragment instead of duplicating it.
overrides_add() {
	local contributor="$1" bucket="$2" dir known found=
	dir="$(_overrides_dir)" || return 1
	for known in "${_overrides_buckets[@]}"; do
		[ "$bucket" = "$known" ] && found=1
	done
	if [ -z "$found" ]; then
		printf '\033[1;31m[overrides]\033[0m unknown bucket "%s"\n' "$bucket" >&2
		return 1
	fi
	mkdir -p "$dir/$bucket"
	cat >"$dir/$bucket/$contributor.yml"
}

# True when any contributor wrote to <bucket>.
_overrides_has() {
	local dir
	dir="$(_overrides_dir)" || return 1
	[ -n "$(ls -A "$dir/$1" 2>/dev/null)" ]
}

# Emits every fragment in <bucket>, each prefixed with a comment naming its
# contributor and indented by <pad> spaces. Blank lines stay blank rather than
# collecting trailing whitespace.
_overrides_emit() {
	local bucket="$1" pad="$2" dir file
	dir="$(_overrides_dir)" || return 1
	for file in "$dir/$bucket"/*.yml; do
		[ -f "$file" ] || continue
		awk -v pad="$pad" -v src="$(basename "${file%.yml}")" '
			BEGIN { for (i = 0; i < pad; i++) indent = indent " "; print indent "# " src }
			{ print (length($0) ? indent $0 : "") }
		' "$file"
	done
}

# overrides_write — merges the staged fragments into docker-compose.overrides.yml.
overrides_write() {
	_overrides_dir >/dev/null || return 1
	{
		echo "# Generated by .devcontainer/scripts/initialize.sh — do not edit."
		echo "#"
		echo "# Rewritten on every container create; anything changed here is lost. What"
		echo "# lands in this file depends on the checkout (linked git worktree or not) and"
		echo "# on which features devcontainer.json declares — see scripts/lib/overrides.sh."
		echo "services:"
		if _overrides_has service || _overrides_has service-volumes; then
			echo "  app:"
			_overrides_emit service 4
			if _overrides_has service-volumes; then
				echo "    volumes:"
				_overrides_emit service-volumes 6
			fi
		else
			# devcontainer.json includes this file unconditionally, so it has to be
			# valid compose even when nothing contributed to it.
			echo "  app: {}"
		fi
		if _overrides_has volumes; then
			echo "volumes:"
			_overrides_emit volumes 2
		fi
	} >"$_overrides_out"
}
