import './startup/custom-sounds';
import './startup/permissions';
import './startup/settings';
import './models/CustomSounds';
import './methods/deleteCustomSound';
import './methods/insertOrUpdateSound';
import './methods/listCustomSounds';
import './methods/uploadCustomSound';
import './publications/customSounds';
