#!/bin/bash

# Initialize the SITE_URL (ROOT_URL) to a default
snapctl set site-url=http://localhost

# Initialize the PORT to a default
snapctl set port=3000

# Initialize the MONGO_URL to a default
snapctl set mongo-url=mongodb://localhost:27017/parties

# Initialize the MONGO_OPLOG_URL to a default
snapctl set mongo-oplog-url=mongodb://localhost:27017/local

# Initialize the protocol to a default
snapctl set https=disable
