export const GO_ROCKET_CHAT_PREFIX = 'https://go.rocket.chat';

export const links = {
	go: {
		accessibilityAndAppearance: `${GO_ROCKET_CHAT_PREFIX}/i/accessibility-and-appearance`,
		accessibilityStatement: `${GO_ROCKET_CHAT_PREFIX}/i/accessibility-statement`,
		airgappedRestriction: `${GO_ROCKET_CHAT_PREFIX}/i/airgapped-restriction`,
		appsDocumentation: `${GO_ROCKET_CHAT_PREFIX}/i/developing-an-app`,
		contactSales: `${GO_ROCKET_CHAT_PREFIX}/i/contact-sales`,
		contactSalesProduct: `${GO_ROCKET_CHAT_PREFIX}/i/contact-sales-product`,
		desktopAppWindows: `${GO_ROCKET_CHAT_PREFIX}/i/hp-desktop-app-windows`,
		desktopAppMac: `${GO_ROCKET_CHAT_PREFIX}/i/hp-desktop-app-mac`,
		desktopAppLinux: `${GO_ROCKET_CHAT_PREFIX}/i/hp-desktop-app-linux`,
		documentation: `${GO_ROCKET_CHAT_PREFIX}/i/hp-documentation`,
		downgrade: `${GO_ROCKET_CHAT_PREFIX}/i/docs-downgrade`,
		e2eeGuide: `${GO_ROCKET_CHAT_PREFIX}/i/e2ee-guide`,
		fingerPrintChangedFaq: `${GO_ROCKET_CHAT_PREFIX}/i/fingerprint-changed-faq`,
		getAddons: `${GO_ROCKET_CHAT_PREFIX}/i/get-addons`,
		glossary: `${GO_ROCKET_CHAT_PREFIX}/i/glossary`,
		homepage: `${GO_ROCKET_CHAT_PREFIX}/home`,
		invite: `${GO_ROCKET_CHAT_PREFIX}/invite?host=open.rocket.chat&path=invite%2F5sBs3a`,
		ldapDocs: `${GO_ROCKET_CHAT_PREFIX}/i/ldap-docs`,
		matrixFederation: `${GO_ROCKET_CHAT_PREFIX}/i/matrix-federation`,
		mobileAppGoogle: `${GO_ROCKET_CHAT_PREFIX}/i/hp-mobile-app-google`,
		mobileAppApple: `${GO_ROCKET_CHAT_PREFIX}/i/hp-mobile-app-apple`,
		omnichannelDocs: `${GO_ROCKET_CHAT_PREFIX}/i/omnichannel-docs`,
		pricing: `${GO_ROCKET_CHAT_PREFIX}/i/see-paid-plan-customize-homepage`,
		pricingProduct: `${GO_ROCKET_CHAT_PREFIX}/i/pricing-product`,
		registerInfoCollected: `${GO_ROCKET_CHAT_PREFIX}/i/register-info-collected`,
		supportPrerequisites: `${GO_ROCKET_CHAT_PREFIX}/i/support-prerequisites`,
		trial: `${GO_ROCKET_CHAT_PREFIX}/i/docs-trial`,
		versionSupport: `${GO_ROCKET_CHAT_PREFIX}/i/version-support`,
		updateProduct: `${GO_ROCKET_CHAT_PREFIX}/i/update-product`,
	},
	desktopAppDownload: 'https://rocket.chat/download',
	enterprise: 'https://www.rocket.chat/enterprise',
	outboundDocs: 'https://docs.rocket.chat/docs/p2p-outbound-messaging',
	privacy: 'https://rocket.chat/privacy',
	retentionPolicy: 'https://docs.rocket.chat/use-rocket.chat/workspace-administration/settings/retention-policies',
	rocketChat: 'https://rocket.chat/',
	rocketChatUpdated: 'https://rocket.chat/updated',
	scaling: 'https://docs.rocket.chat/deploy/scaling-rocket.chat',
	terms: 'https://rocket.chat/terms',
	updatingRocketChat: 'https://docs.rocket.chat/v1/docs/en/updating-rocketchat',
	webhooks: 'https://docs.rocket.chat/use-rocket.chat/omnichannel/webhooks',
} as const;
