import './lib/accounts';
import './lib/collections';
import './lib/customEventPolyfill';
import './lib/iframeCommands';
import './lib/menu';
import './lib/Modernizr';
import './lib/parentTemplate';
import './lib/codeMirror/codeMirror';
import './lib/textarea-cursor';
import './views/cmsPage.html';
import './views/fxos.html';
import './views/modal.html';
import './views/404/roomNotFound.html';
import './views/404/invalidSecretURL.html';
import './views/app/audioNotification.html';
import './views/app/burger.html';
import './views/app/createChannel.html';
import './views/app/editStatus.html';
import './views/app/editStatus.css';
import './views/app/fullModal.html';
import './views/app/home.html';
import './views/app/notAuthorized.html';
import './views/app/pageContainer.html';
import './views/app/pageSettingsContainer.html';
import './views/app/room.html';
import './views/app/roomSearch.html';
import './views/app/secretURL.html';
import './views/app/userSearch.html';
import './views/app/videoCall/videoButtons.html';
import './views/app/videoCall/videoCall.html';
import './views/app/photoswipe.html';
import './views/cmsPage';
import './views/fxos';
import './views/modal';
import './views/404/roomNotFound';
import './views/app/burger';
import './views/app/createChannel';
import './views/app/editStatus';
import './views/app/fullModal';
import './views/app/home';
import './views/app/directory';
import './views/app/roomSearch';
import './views/app/secretURL';
import './views/app/videoCall/videoButtons';
import './views/app/videoCall/videoCall';
import './views/app/photoswipe';
import './components/icon';
import './components/table.html';
import './components/table';
import './components/tabs';
import './components/popupList.html';
import './components/popupList';
import './components/selectDropdown.html';

import './components/header/header.html';
import './components/header/header';
import './components/header/headerRoom.html';
import './components/header/headerRoom';
import './components/contextualBar.html';
import './components/contextualBar';

export { ChatMessages } from './lib/chatMessages';
export { fileUpload } from './lib/fileUpload';
export { MsgTyping } from './lib/msgTyping';
export { KonchatNotification } from './lib/notification';
export { Login, animationSupport, animeBack, Button, preLoadImgs } from './lib/rocket';
export { AudioRecorder } from './lib/recorderjs/audioRecorder';
export { VideoRecorder } from './lib/recorderjs/videoRecorder';
export { chatMessages } from './views/app/room';
