export { saveUser } from './saveUser';
export { saveUserIdentity } from './saveUserIdentity';
export { sendMessage } from './sendMessage';
export { setEmail } from './setEmail';
export { getStatusText } from './getStatusText';
export { setUserAvatar } from './setUserAvatar';
export { _setUsername, setUsername, setUsernameWithValidation } from './setUsername';
export { unarchiveRoom } from './unarchiveRoom';
export { updateMessage } from './updateMessage';
export { validateCustomFields } from './validateCustomFields';
export { validateName } from './validateName';
