// The room fields that clients may read. Keep in step with `roomFields` of the
// monolith, which has no package to share it from.
export const roomFields = {
  _id: 1,
  name: 1,
  fname: 1,
  t: 1,
  cl: 1,
  u: 1,
  lm: 1,
  teamId: 1,
  teamMain: 1,
  topic: 1,
  announcement: 1,
  announcementDetails: 1,
  muted: 1,
  unmuted: 1,
  _updatedAt: 1,
  archived: 1,
  description: 1,
  default: 1,
  customFields: 1,
  lastMessage: 1,
  retention: 1,
  prid: 1,
  avatarETag: 1,
  usersCount: 1,
  msgs: 1,
  tags: 1,
  sms: 1,
  code: 1,
  joinCodeRequired: 1,
  open: 1,
  label: 1,
  ro: 1,
  reactWhenReadOnly: 1,
  sysMes: 1,
  sentiment: 1,
  broadcast: 1,
  encrypted: 1,
  e2eKeyId: 1,
  livechatData: 1,
  priorityId: 1,
  priorityWeight: 1,
  slaId: 1,
  estimatedWaitingTimeQueue: 1,
  v: 1,
  contactId: 1,
  verified: 1,
  departmentId: 1,
  servedBy: 1,
  source: 1,
  transcriptRequest: 1,
  onHold: 1,
  metrics: 1,
  ts: 1,
  waitingResponse: 1,
  queuedAt: 1,
  federated: 1,
  federation: 1,
  usernames: 1,
  uids: 1,
  usersWaitingForE2EKeys: 1,
  abacAttributes: 1,
} as const;

// The fields that the room lookups of the real API never return.
export const excludedRoomFields = {
  joinCode: 0,
  members: 0,
  importIds: 0,
  e2e: 0,
} as const;
