import { startCoreDependencies } from './startup/coreDependencies';
import '../lib/absoluteUrl';
import './models/startup';
import '../ee/server/models/startup';

void startCoreDependencies().then(() => {
	require('./configureLogLevel');
	require('./startup');

	require('../lib/oauthRedirectUriServer');
	require('./lib/logger/startup');
	require('./importPackages');
	require('../imports/startup/server');
	require('../app/lib/server/startup');

	require('../ee/server/startup');
	require('../ee/server');
	require('./lib/pushConfig');
	require('./configuration/accounts_meld');
	require('./configuration/ldap');
	require('./methods/OEmbedCacheCleanup');
	require('./methods/addAllUserToRoom');
	require('./methods/addRoomLeader');
	require('./methods/addRoomModerator');
	require('./methods/addRoomOwner');
	require('./methods/afterVerifyEmail');
	require('./methods/browseChannels');
	require('./methods/canAccessRoom');
	require('./methods/channelsList');
	require('./methods/createDirectMessage');
	require('./methods/deleteFileMessage');
	require('./methods/deleteUser');
	require('./methods/eraseRoom');
	require('./methods/getAvatarSuggestion');
	require('./methods/getPasswordPolicy');
	require('./methods/getRoomById');
	require('./methods/getRoomIdByNameOrId');
	require('./methods/getRoomNameById');
	require('./methods/getSetupWizardParameters');
	require('./methods/getTotalChannels');
	require('./methods/getUsersOfRoom');
	require('./methods/hideRoom');
	require('./methods/ignoreUser');
	require('./methods/loadHistory');
	require('./methods/loadLocale');
	require('./methods/loadMissedMessages');
	require('./methods/loadNextMessages');
	require('./methods/loadSurroundingMessages');
	require('./methods/logoutCleanUp');
	require('./methods/messageSearch');
	require('./methods/muteUserInRoom');
	require('./methods/openRoom');
	require('./methods/readMessages');
	require('./methods/readThreads');
	require('./methods/registerUser');
	require('./methods/removeRoomLeader');
	require('./methods/removeRoomModerator');
	require('./methods/removeRoomOwner');
	require('./methods/removeUserFromRoom');
	require('./methods/reportMessage');
	require('./methods/requestDataDownload');
	require('./methods/resetAvatar');
	require('./methods/roomNameExists');
	require('./methods/saveUserPreferences');
	require('./methods/saveUserProfile');
	require('./methods/sendConfirmationEmail');
	require('./methods/sendForgotPasswordEmail');
	require('./methods/setAvatarFromService');
	require('./methods/setUserActiveStatus');
	require('./methods/setUserPassword');
	require('./methods/toggleFavorite');
	require('./methods/unmuteUserInRoom');
	require('./methods/userPresence');
	require('./methods/userSetUtcOffset');
	require('./publications/messages');
	require('./publications/room');
	require('./publications/settings');
	require('./publications/spotlight');
	require('./publications/subscription');
	require('./routes/avatar');
	require('./routes/health');
	require('./routes/i18n');
	require('./routes/timesync');
	require('./routes/userDataDownload');
	require('./stream/stdout');

	require('./features/EmailInbox/index');
});
