import './actionButton';
import './messageType';
import './snippetMessage';
import './page/snippetPage.html';
import './page/snippetPage';
import './tabBar/tabBar';
import './tabBar/views/snippetedMessages.html';
import './tabBar/views/snippetedMessages';
import './page/stylesheets/snippetPage.css';
