export const AI_LICENSE_MODULE = 'chat.rocket.rc-ai';

export const AI_SEARCH_PAGE_SIZE = 5;
export const MAX_INTELLIGENT_SEARCH_RESULTS = 50;
export const MAX_SEARCH_FILTER_VALUES = 25;
export const MAX_UNIFIED_SEARCH_RESULTS = 10;
export const MAX_ROOM_SEARCH_PATTERN_LENGTH = 64;
export const MAX_SOURCE_MESSAGE_LENGTH = 700;
export const MAX_SEARCH_ANSWER_MESSAGES = 20;
export const MAX_SEARCH_ANSWER_TEXT_LENGTH = 1600;
