/** @deprecated */
export enum ElementType {
	PLAIN_TEXT = 'plain_text',
	MARKDOWN = 'mrkdwn',
	DIVIDER = 'divider',
	SECTION = 'section',
	INPUT = 'input',
	CONDITIONAL = 'conditional',
	IMAGE = 'image',
	ACTIONS = 'actions',
	CONTEXT = 'context',
	BUTTON = 'button',
	OVERFLOW = 'overflow',
	PLAIN_TEXT_INPUT = 'plain_text_input',
	CONVERSATION_SELECT = 'conversations_select',
	CHANNEL_SELECT = 'channels_select',
	USER_SELECT = 'users_select',
	STATIC_SELECT = 'static_select',
	MULTI_STATIC_SELECT = 'multi_static_select',
	DATEPICKER = 'datepicker',
	LINEAR_SCALE = 'linear_scale',
	TAB = 'tab',
}
