RocketChat.theme.addPublicColor "content-background-color", "#FFF"
RocketChat.theme.addPublicColor "primary-background-color", "#04436A"
RocketChat.theme.addPublicColor "secondary-background-color", "#F4F4F4"
RocketChat.theme.addPublicColor "tertiary-background-color", "#EAEAEA"
RocketChat.theme.addPublicColor "primary-font-color", "#444444"
RocketChat.theme.addPublicColor "secondary-font-color", "#7F7F7F"
RocketChat.theme.addPublicColor "tertiary-font-color", "rgba(255, 255, 255, 0.6)"
RocketChat.theme.addPublicColor "quaternary-font-color", "#FFF"
RocketChat.theme.addPublicColor "input-font-color", "rgba(255, 255, 255, 0.85)"
RocketChat.theme.addPublicColor "link-font-color", "#008CE3"
RocketChat.theme.addPublicColor "info-font-color", "#AAAAAA"
RocketChat.theme.addPublicColor "info-active-font-color", "#FF0000"
RocketChat.theme.addPublicColor "smallprint-font-color", "#C2E7FF"
RocketChat.theme.addPublicColor "smallprint-hover-color", "#FFFFFF"
RocketChat.theme.addPublicColor "status-online", "#35AC19"
RocketChat.theme.addPublicColor "status-offline", "rgba(150, 150, 150, 0.50)"
RocketChat.theme.addPublicColor "status-busy", "#D30230"
RocketChat.theme.addPublicColor "status-away", "#FCB316"
RocketChat.theme.addPublicColor "code-background", "#F8F8F8"
RocketChat.theme.addPublicColor "code-border", "#CCC"
RocketChat.theme.addPublicColor "code-color", "#333"
RocketChat.theme.addPublicColor "blockquote-background", "#CCC"
RocketChat.theme.addPublicColor "message-hover-background-color", "#f9f9f9"
RocketChat.theme.addPublicColor "active-channel-background-color", "rgba(255, 255, 255, 0.075)"
RocketChat.theme.addPublicColor "active-channel-font-color", "rgba(255, 255, 255, 0.75)"
RocketChat.theme.addPublicColor "custom-scrollbar-color", "rgba(255, 255, 255, 0.05)"
RocketChat.theme.addPublicColor "action-buttons-color", "#FFF"
RocketChat.theme.addPublicColor "clean-buttons-color", "rgba(0, 0, 0, 0.025)"
RocketChat.theme.addPublicColor "unread-notification-color", "#1dce73"

