export class ClientResultFactory {
	getInstance(creator, endpointUrl) {
		switch (creator) {
			case 'dbsearch':
				return new SolrProvider(creator, endpointUrl);
		}
	}
}

class SolrProvider {
	constructor(creator, endpointUrl) {
		this.creator = creator;
		this.endpointUrl = endpointUrl;
	}

	/**
	 * Executes an asynchronous data retrieval and hands it over to the callback as single parameter
	 * @return Promise
	 */
	executeSearch(queryParameters) {
		console.log("executeSearch " + this.endpointUrl);
		return new Promise(function (resolve, reject) {
			if(mock) {
				resolve(SolrProvider.transformResponse(mockData));
			} else {
				$.ajax({
					url: this.endpointUrl,
					dataType: "jsonp",
					jsonp: 'json.wrf',
					success: function (data) {
						resolve(SolrProvider.transformResponse(data));
					},
					error: function(error){
						reject(new Error('no-dbsearch-result'));
					}
				});
			}
			}
		)
	}

	static transformResponse(data) {
		for (var j = 0; j < data.response.docs.length; j++) {
			var doc = data.response.docs[j];
			var hl = data.highlighting[doc.id];
			var body = "";
			if (hl && hl['dbsearch_highlight_t_de'] && hl['dbsearch_highlight_t_de'].length > 0) {
				for (var i = 0; i < hl['dbsearch_highlight_t_de'].length; i++) {
					body += hl['dbsearch_highlight_t_de'][i] + " ";
				}
			}
			doc['body'] = body;
		}
		console.log(data);
		return data;
	}
}

let mock = true;

//temporär wenn nicht im Intranet: JSON statisch erzeugen
var mockData = {
	"responseHeader": {
		"status": 0,
		"QTime": 1431,
		"params": {
			"facet.field": ["{!ex=selSource}dbsearch_source_path", "{!ex=selAuthor}dbsearch_author_ss", "{!ex=selKeywords}dbsearch_keywords_ss", "{!ex=selType}dbsearch_content_type_aggregated_s"],
			"f.dbsearch_source_path.facet.limit": "-1",
			"AuthenticatedUserDomain": "BKU",
			"AuthenticatedUserName": "ruedigerkurz|Ruediger.Kurz@deutschebahn.com",
			"json.nl": "map",
			"f.dbsearch_author_ss.facet.limit": "20",
			"boostlang": "de",
			"dbsearch_prefilter": "true",
			"rows": "8",
			"facet.query": ["{!key=all ex=dateFacet}id:*", "{!key=last_day ex=dateFacet}dbsearch_pub_date_tdt:[NOW-1DAY TO *]", "{!key=last_week ex=dateFacet}dbsearch_pub_date_tdt:[NOW-7DAYS TO *]", "{!key=last_month ex=dateFacet}dbsearch_pub_date_tdt:[NOW-1MONTH TO *]", "{!key=last_year ex=dateFacet}dbsearch_pub_date_tdt:[NOW-1YEAR TO *]", "{!key=older ex=dateFacet}dbsearch_pub_date_tdt:[* TO NOW-1YEAR]", "{!key=missing ex=dateFacet}-dbsearch_pub_date_tdt:[* TO *]"],
			"mcf": "true",
			"f.dbsearch_keywords_ss.facet.limit": "20",
			"q": "test",
			"json.wrf": "jQuery221010457950976332464_1489574282541",
			"f.dbsearch_author_ss.facet.missing": "true",
			"dbsearch_context": "dbsearch",
			"facet": "true",
			"wt": "json"
		}
	},
	"securityStatus": "ok",
	"response": {
		"numFound": 139378,
		"start": 0,
		"docs": [{
			"dbsearch_mod_date_tdt": "2017-03-01T10:44:11Z",
			"dbsearch_source_name_s": "Wiki-Pool DB Systel",
			"dbsearch_space_id_s": "eq2016",
			"dbsearch_source_type_s": "confluence",
			"id": "https://dbsystel.wiki.intranet.deutschebahn.com/wiki/pages/viewpage.action?pageId=57855715",
			"dbsearch_pub_date_tdt": "2017-03-01T09:58:18Z",
			"dbsearch_space_name_t": "Einstiegsqualifizierung DB Systel",
			"dbsearch_content_type_s": "text/html",
			"dbsearch_content_type_aggregated_s": "html",
			"dbsearch_keywords_txt": ["test"],
			"dbsearch_link_s": "https://dbsystel.wiki.intranet.deutschebahn.com/wiki/pages/viewpage.action?pageId=57855715",
			"dbsearch_doctype_s": "Document",
			"dbsearch_author_t": "Mohammad-Sharif Moradi",
			"dbsearch_content_size_l": 554,
			"dbsearch_title_s": "EQ-Praktikanten bei der DB Systel",
			"dbsearch_excerpt_s": "† Einstiegsqualifizierung (EQ): Berichte Was bedeutet EQ Praktikum†Programm? Einstiegsqualifizierung Programm ist eine Mˆglichkeit, Chance und Zugang †f¸r junge†Menschen mit Migrationshintergrund. Es",
			"dbsearch_language_s": "de",
			"[elevated]": false
		}, {
			"dbsearch_source_type_s": "sharepoint",
			"dbsearch_source_name_s": "TIKA",
			"dbsearch_pub_date_tdt": "2017-03-10T15:04:30Z",
			"dbsearch_content_type_s": "application/pdf",
			"dbsearch_content_type_aggregated_s": "pdf",
			"dbsearch_space_id_s": "Muster WA / WA Example",
			"id": "https://m00014.sharepoint.noncd.rz.db.de/workingareas/musterwawaexample/Documents/Projekt%202/Test%20Anna%2023.pdf",
			"dbsearch_space_name_t": "Muster WA / WA Example",
			"dbsearch_content_size_l": 85588,
			"dbsearch_mod_date_tdt": "2017-03-10T15:04:30Z",
			"dbsearch_link_s": "https://tika.sharepoint.noncd.rz.db.de/workingareas/musterwawaexample/Documents/Projekt%202/Test%20Anna%2023.pdf",
			"dbsearch_title_s": "Test Anna 23",
			"dbsearch_classifier_ss": ["gassc"],
			"dbsearch_extracted_pub_date_tdt": "2017-03-10T15:04:01Z",
			"dbsearch_extracted_mod_date_tdt": "2017-03-10T15:04:01Z",
			"dbsearch_excerpt_s": "Test Anna 23 Anna 01.03.2017 Mit Kommentaren am 10.03.2017 Und noch mehr Kommentare am 10.03.2017",
			"dbsearch_language_s": "de",
			"dbsearch_doctype_s": "Document",
			"[elevated]": false
		}, {
			"dbsearch_source_type_s": "sharepoint",
			"dbsearch_source_name_s": "TIKA",
			"dbsearch_pub_date_tdt": "2017-03-10T15:03:05Z",
			"dbsearch_content_type_s": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
			"dbsearch_content_type_aggregated_s": "msword",
			"dbsearch_space_id_s": "Muster WA / WA Example",
			"id": "https://m00014.sharepoint.noncd.rz.db.de/workingareas/musterwawaexample/Documents/Projekt%202/Test%20Anna%2023.docx",
			"dbsearch_space_name_t": "Muster WA / WA Example",
			"dbsearch_content_size_l": 21276,
			"dbsearch_mod_date_tdt": "2017-03-10T15:03:05Z",
			"dbsearch_link_s": "https://tika.sharepoint.noncd.rz.db.de/workingareas/musterwawaexample/Documents/Projekt%202/Test%20Anna%2023.docx",
			"dbsearch_title_s": "Test Anna 23",
			"dbsearch_classifier_ss": ["gassc"],
			"dbsearch_extracted_pub_date_tdt": "2015-12-04T11:25:00Z",
			"dbsearch_extracted_mod_date_tdt": "2017-03-10T15:02:47Z",
			"dbsearch_excerpt_s": "Test Anna 23 Anna 01.03.2017 Mit Kommentaren am 10.03.2017 Und noch mehr Kommentare am 10.03.2017",
			"dbsearch_language_s": "de",
			"dbsearch_doctype_s": "Document",
			"[elevated]": false
		}, {
			"dbsearch_mod_date_tdt": "2017-03-01T12:21:09Z",
			"dbsearch_source_name_s": "Athene",
			"dbsearch_source_type_s": "Athene",
			"id": "https://athene.intranet.deutschebahn.com/athene/livelink?func=ll&objAction=overview&objID=25748005",
			"dbsearch_pub_date_tdt": "2017-03-01T12:21:09Z",
			"dbsearch_content_type_s": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
			"dbsearch_content_type_aggregated_s": "mspowerpoint",
			"dbsearch_link_s": "https://athene.intranet.deutschebahn.com/athene/livelink?func=ll&objAction=overview&objID=25748005",
			"dbsearch_content_size_l": 241520,
			"dbsearch_title_s": "Umgebungen - Instanzen.pptx",
			"dbsearch_extracted_title_s": "Test",
			"dbsearch_extracted_pub_date_tdt": "2005-02-21T07:36:49Z",
			"dbsearch_extracted_mod_date_tdt": "2017-03-01T12:20:34Z",
			"dbsearch_excerpt_s": "DB Systel GmbH | PAISY-Point | I.LPA 54 | 13.07.2016 PAISY CS Umgebungen ñ Instanzen Teilweise freigegeben Hinweis: F¸r externe Pr‰sentationen bitte immer eine Titelfolie mit der Ressort-Farbe",
			"dbsearch_language_s": "de",
			"dbsearch_doctype_s": "Document",
			"[elevated]": false
		}, {
			"dbsearch_mod_date_tdt": "2017-02-22T14:28:03Z",
			"dbsearch_source_name_s": "Wiki-Pool DB Systel",
			"dbsearch_space_id_s": "dbsystel",
			"dbsearch_source_type_s": "confluence",
			"id": "https://dbsystel.wiki.intranet.deutschebahn.com/wiki/pages/viewpage.action?pageId=57850201",
			"dbsearch_pub_date_tdt": "2017-02-22T14:14:28Z",
			"dbsearch_space_name_t": "DB Systel Wiki",
			"dbsearch_content_type_s": "text/html",
			"dbsearch_content_type_aggregated_s": "html",
			"dbsearch_keywords_txt": ["test", "protokoll"],
			"dbsearch_link_s": "https://dbsystel.wiki.intranet.deutschebahn.com/wiki/pages/viewpage.action?pageId=57850201",
			"dbsearch_doctype_s": "Document",
			"dbsearch_author_t": "Peter Markwart",
			"dbsearch_content_size_l": 5798,
			"dbsearch_title_s": "D.IPB 44 - Protokoll - Abteilungsmeeting 22.02.17",
			"dbsearch_excerpt_s": "† † † † Seitennavigation >>† Meetings und Protokolle der D.IPB 44 † Allgemeine Daten Thema des Meetings Abteilungsmeeting Datum 22.02.2017 Zeitraum 13:30 - 14:30 Uhr Ort Silberturm J02 03 Teilnehmer",
			"dbsearch_language_s": "de",
			"[elevated]": false
		}, {
			"dbsearch_mod_date_tdt": "2017-01-26T09:52:08Z",
			"dbsearch_source_name_s": "Wiki-Pool DB Systel",
			"dbsearch_space_id_s": "dbsystel",
			"dbsearch_source_type_s": "confluence",
			"id": "https://dbsystel.wiki.intranet.deutschebahn.com/wiki/pages/viewpage.action?pageId=56552993",
			"dbsearch_pub_date_tdt": "2017-01-26T09:30:16Z",
			"dbsearch_space_name_t": "DB Systel Wiki",
			"dbsearch_content_type_s": "text/html",
			"dbsearch_content_type_aggregated_s": "html",
			"dbsearch_keywords_txt": ["test", "protokoll"],
			"dbsearch_link_s": "https://dbsystel.wiki.intranet.deutschebahn.com/wiki/pages/viewpage.action?pageId=56552993",
			"dbsearch_doctype_s": "Document",
			"dbsearch_author_t": "Peter Markwart",
			"dbsearch_content_size_l": 6318,
			"dbsearch_title_s": "D.IPB 44 - Protokoll - Abteilungsmeeting 25.01.17",
			"dbsearch_excerpt_s": "† † † † Seitennavigation >>† Meetings und Protokolle der D.IPB 44 † Allgemeine Daten Thema des Meetings Abteilungsmeeting Datum 25.01.2017 Zeitraum 13:30 - 15:30 Uhr Ort Silberturm J02 03 Teilnehmer",
			"dbsearch_language_s": "de",
			"[elevated]": false
		}, {
			"dbsearch_mod_date_tdt": "2017-01-27T15:34:56Z",
			"dbsearch_source_name_s": "Athene",
			"dbsearch_source_type_s": "Athene",
			"id": "https://athene.intranet.deutschebahn.com/athene/livelink?func=ll&objAction=overview&objID=27775601",
			"dbsearch_pub_date_tdt": "2017-01-27T15:34:56Z",
			"dbsearch_content_type_s": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
			"dbsearch_content_type_aggregated_s": "mspowerpoint",
			"dbsearch_link_s": "https://athene.intranet.deutschebahn.com/athene/livelink?func=ll&objAction=overview&objID=27775601",
			"dbsearch_content_size_l": 871516,
			"dbsearch_title_s": "170126 - Info GBR Vertrieb Status KFMS.pptx",
			"dbsearch_extracted_title_s": "Test",
			"dbsearch_extracted_pub_date_tdt": "2005-02-21T07:36:49Z",
			"dbsearch_extracted_mod_date_tdt": "2017-01-27T07:45:52Z",
			"dbsearch_excerpt_s": "Zukunft Bahn Projekt Kundenfeedbackmanagement 30.01.2017 Hinweis: ÑVielen Dank f¸r Ihre Aufmerksamkeitì kann auch durch ein anderes Abschlusszitat oder eine Botschaft ersetzt werden. 1 ‹bergang ZuBa",
			"dbsearch_language_s": "de",
			"dbsearch_doctype_s": "Document",
			"[elevated]": false
		}, {
			"dbsearch_mod_date_tdt": "2017-01-26T13:40:31Z",
			"dbsearch_source_name_s": "Athene",
			"dbsearch_source_type_s": "Athene",
			"id": "https://athene.intranet.deutschebahn.com/athene/livelink?func=ll&objAction=overview&objID=27761612",
			"dbsearch_pub_date_tdt": "2017-01-26T13:40:31Z",
			"dbsearch_content_type_s": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
			"dbsearch_content_type_aggregated_s": "mspowerpoint",
			"dbsearch_link_s": "https://athene.intranet.deutschebahn.com/athene/livelink?func=ll&objAction=overview&objID=27761612",
			"dbsearch_content_size_l": 1166289,
			"dbsearch_title_s": "170124 - 7. Review Board gezeigte Version.pptx",
			"dbsearch_extracted_title_s": "Test",
			"dbsearch_extracted_pub_date_tdt": "2005-02-21T07:36:49Z",
			"dbsearch_extracted_mod_date_tdt": "2017-01-25T07:30:10Z",
			"dbsearch_excerpt_s": "Zukunft Bahn Projekt Kundenfeedbackmanagement 7. Review Board Projekt Kundenfeedbackmanagement 24.01.2017 Hinweis: ÑVielen Dank f¸r Ihre Aufmerksamkeitì kann auch durch ein anderes Abschlusszitat",
			"dbsearch_language_s": "de",
			"dbsearch_doctype_s": "Document",
			"[elevated]": false
		}]
	},
	"facet_counts": {
		"facet_queries": {
			"all": 139378,
			"last_day": 11,
			"last_week": 207,
			"last_month": 843,
			"last_year": 20724,
			"older": 118468,
			"missing": 186
		},
		"facet_fields": {
			"dbsearch_source_path": {
				"Athene": 120965,
				"BahnWiki": 814,
				"BahnWiki/BEAM-Wiki": 49,
				"BahnWiki/BahnWiki+-+Das+Wiki+der+Bahn": 17,
				"BahnWiki/CIOFernverkehr": 44,
				"BahnWiki/Controlling-Fernverkehr": 23,
				"BahnWiki/Corporate+Real+Estate+Wiki": 3,
				"BahnWiki/DB+Cargo+Data+Management": 8,
				"BahnWiki/DB+Institute+of+Technology": 29,
				"BahnWiki/DBMAS-Wiki": 19,
				"BahnWiki/DS.C": 275,
				"BahnWiki/Dual-Studierenden+Wiki": 3,
				"BahnWiki/Enterprise+Mobility+Management": 3,
				"BahnWiki/FZI-PS": 8,
				"BahnWiki/ISI+Wiki": 35,
				"BahnWiki/ITK-Wiki": 113,
				"BahnWiki/Infrastrukturstammdaten": 3,
				"BahnWiki/KIT+Kommunikation.Information.Technologie": 33,
				"BahnWiki/Mafo+Wiki": 29,
				"BahnWiki/Microsoft+Office+2010": 6,
				"BahnWiki/PSSx": 3,
				"BahnWiki/Prometheus": 8,
				"BahnWiki/Serviceportal": 54,
				"BahnWiki/Wiki+d%27Euro+Cargo+Rail": 8,
				"BahnWiki/Wiki-Safety": 1,
				"BahnWiki/iTWO+Wiki": 40,
				"Blogs": 141,
				"Blogs/Agile+Gedanken": 2,
				"Blogs/Agile+Round+Table": 2,
				"Blogs/Alles+im+gr%C3%BCnen+Bereich": 1,
				"Blogs/Architektur+vs.+Details": 1,
				"Blogs/Bieberblog": 2,
				"Blogs/Code+Zukunft+Kommunikation": 1,
				"Blogs/DB+Knowledge+Core": 1,
				"Blogs/DCS+Dialog": 1,
				"Blogs/Datenschutz": 1,
				"Blogs/Der+unbekannte+Dritte": 31,
				"Blogs/Design+Thinking": 4,
				"Blogs/G+1.05+Blog": 4,
				"Blogs/GF+en+Blog": 5,
				"Blogs/INetBlog": 1,
				"Blogs/JUC%26%23039%3Bs+World": 1,
				"Blogs/LVD+8+News+-+Strategy+and+Consulting": 3,
				"Blogs/Logbuch+der+Ver%C3%A4nderungen": 2,
				"Blogs/Mobile+Development": 12,
				"Blogs/Neues+von+Q": 18,
				"Blogs/Notes+on+Notes": 7,
				"Blogs/Nummer+32": 2,
				"Blogs/Plattform+News": 3,
				"Blogs/Return+of+Developers": 10,
				"Blogs/SXSW": 2,
				"Blogs/Securing+the+Land+of+01": 2,
				"Blogs/Sendungsbewusstsein": 4,
				"Blogs/Small+Solutions": 3,
				"Blogs/Technologie-+und+Innovationsmanagement": 5,
				"Blogs/User+Experience": 10,
				"DB+Personalportal": 12,
				"DB+Systel+Forum": 12,
				"DB+Systel+Forum/Biete+und+Suche": 1,
				"DB+Systel+Forum/Rollout+DB+Communicator": 4,
				"DB+Systel+Forum/SW-Entwicklung": 2,
				"DB+Systel+Forum/Strategie": 2,
				"DB+Systel+Forum/Web+2.0%3A+Neues%2C+Fragen%2C+Ideen%2C+Tipps+und+Tricks": 3,
				"DB+im+Internet": 2779,
				"DB+im+Internet/%D0%94%D0%91+%D0%A8%D0%B5%D0%BD%D0%BA%D0%B5%D1%80+%D0%9C%D0%B0%D0%BA%D0%B5%D0%B4%D0%BE%D0%BD%D0%B8%D1%98%D0%B0": 1,
				"DB+im+Internet/%E5%BE%B7%E9%90%B5%E4%BF%A1%E5%8F%AF%E5%8F%B0%E7%81%A3": 51,
				"DB+im+Internet/%E5%BE%B7%E9%93%81%E4%BF%A1%E5%8F%AF%E5%9C%A8%E4%B8%AD%E5%9B%BD": 7,
				"DB+im+Internet/+DB+Schenker+Norway": 9,
				"DB+im+Internet/Anlagentechnik%2C+Bautechnik+und+ITK": 11,
				"DB+im+Internet/Bahnbau+Gruppe": 1,
				"DB+im+Internet/BeMobility": 46,
				"DB+im+Internet/CDN+Test": 10,
				"DB+im+Internet/DB+-+Pressestelle+-+Berlin": 7,
				"DB+im+Internet/DB+-+Pressestelle+-+D%C3%BCsseldorf": 10,
				"DB+im+Internet/DB+-+Pressestelle+-+Frankfurt": 1,
				"DB+im+Internet/DB+-+Pressestelle+-+Hamburg": 3,
				"DB+im+Internet/DB+-+Pressestelle+-+M%C3%BCnchen": 8,
				"DB+im+Internet/DB+-+Pressestelle+-+Stuttgart": 6,
				"DB+im+Internet/DB+-+Pressestelle+Leipzig": 5,
				"DB+im+Internet/DB+Cargo+-+Danmark": 14,
				"DB+im+Internet/DB+Cargo+-+Romania": 3,
				"DB+im+Internet/DB+Cargo+AG": 50,
				"DB+im+Internet/DB+Cargo+BTT+GmbH": 6,
				"DB+im+Internet/DB+Cargo+Polska+S.A.": 11,
				"DB+im+Internet/DB+Cargo+UK": 12,
				"DB+im+Internet/DB+Cargo+in+Italy": 1,
				"DB+im+Internet/DB+Cargo+in+Nederland": 3,
				"DB+im+Internet/DB+Dialog+GmbH": 2,
				"DB+im+Internet/DB+Energie": 6,
				"DB+im+Internet/DB+Engineering+%26+Consulting": 30,
				"DB+im+Internet/DB+Fahrzeuginstandhaltung": 12,
				"DB+im+Internet/DB+Heavy+Maintenance": 27,
				"DB+im+Internet/DB+Konzern": 108,
				"DB+im+Internet/DB+Management+Consulting": 2,
				"DB+im+Internet/DB+Museum": 9,
				"DB+im+Internet/DB+Netz+AG": 99,
				"DB+im+Internet/DB+Port+Szczecin": 12,
				"DB+im+Internet/DB+Schenker": 25,
				"DB+im+Internet/DB+Schenker+%C3%96sterreich+-+Logistik-+und+Transportunternehmen": 3,
				"DB+im+Internet/DB+Schenker+%D0%B2+%D0%91%D0%B5%D0%BB%D0%B0%D1%80%D1%83%D1%81%D0%B8": 2,
				"DB+im+Internet/DB+Schenker+%D0%B2+%D0%91%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D0%B8%D1%8F": 1,
				"DB+im+Internet/DB+Schenker+%D0%B2+%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B5": 15,
				"DB+im+Internet/DB+Schenker++%CE%95%CE%BB%CE%BB%CE%AC%CE%B4%CE%B1": 1,
				"DB+im+Internet/DB+Schenker++Greece+": 7,
				"DB+im+Internet/DB+Schenker++Macedonia": 6,
				"DB+im+Internet/DB+Schenker++in+Bulgaria": 9,
				"DB+im+Internet/DB+Schenker+-+P%C5%99eprava+a+logistika": 8,
				"DB+im+Internet/DB+Schenker+-+Transport+and+Logistics": 17,
				"DB+im+Internet/DB+Schenker+Argentina": 5,
				"DB+im+Internet/DB+Schenker+Arkas+T%C3%BCrkiye": 2,
				"DB+im+Internet/DB+Schenker+Arkas+Turkey": 6,
				"DB+im+Internet/DB+Schenker+Australia+%2F+New+Zealand": 13,
				"DB+im+Internet/DB+Schenker+Austria+-+Transportation+and+Logistics": 12,
				"DB+im+Internet/DB+Schenker+BTT+GmbH": 2,
				"DB+im+Internet/DB+Schenker+Chile+Countrysite": 2,
				"DB+im+Internet/DB+Schenker+Corporate+Layout+2014": 1,
				"DB+im+Internet/DB+Schenker+France+site": 9,
				"DB+im+Internet/DB+Schenker+Hrvatska": 1,
				"DB+im+Internet/DB+Schenker+Italia": 9,
				"DB+im+Internet/DB+Schenker+Italy": 19,
				"DB+im+Internet/DB+Schenker+Latvia+-+Transportation+and+Logistics": 5,
				"DB+im+Internet/DB+Schenker+Latvia+-+Transports+un+Lo%C4%A3istika": 3,
				"DB+im+Internet/DB+Schenker+Lietuva": 22,
				"DB+im+Internet/DB+Schenker+Logistics+Bosnia+and+Herzegovina": 6,
				"DB+im+Internet/DB+Schenker+Logistics+Romania": 7,
				"DB+im+Internet/DB+Schenker+Logistics+Romania+++": 2,
				"DB+im+Internet/DB+Schenker+Logistics+UK": 20,
				"DB+im+Internet/DB+Schenker+Logistics+in+Croatia": 7,
				"DB+im+Internet/DB+Schenker+Logistics+in+Poland": 2,
				"DB+im+Internet/DB+Schenker+Malaysia": 57,
				"DB+im+Internet/DB+Schenker+Norge": 5,
				"DB+im+Internet/DB+Schenker+Peru": 8,
				"DB+im+Internet/DB+Schenker+Poland": 4,
				"DB+im+Internet/DB+Schenker+Privpak": 4,
				"DB+im+Internet/DB+Schenker+Russia": 1,
				"DB+im+Internet/DB+Schenker+Slovenia": 7,
				"DB+im+Internet/DB+Schenker+Slovenija": 1,
				"DB+im+Internet/DB+Schenker+Sverige": 22,
				"DB+im+Internet/DB+Schenker+Sweden": 8,
				"DB+im+Internet/DB+Schenker+Taiwan": 59,
				"DB+im+Internet/DB+Schenker+Transa": 1,
				"DB+im+Internet/DB+Schenker+em+Angola": 3,
				"DB+im+Internet/DB+Schenker+em+Portugal": 11,
				"DB+im+Internet/DB+Schenker+en+Am%C3%A9rica+Latina": 3,
				"DB+im+Internet/DB+Schenker+en+Guatemala": 2,
				"DB+im+Internet/DB+Schenker+en+Mexico+++": 2,
				"DB+im+Internet/DB+Schenker+en+Panam%C3%A1": 3,
				"DB+im+Internet/DB+Schenker+en+Venezuela+": 2,
				"DB+im+Internet/DB+Schenker+i+Danmark": 5,
				"DB+im+Internet/DB+Schenker+in+Angola": 6,
				"DB+im+Internet/DB+Schenker+in+Asia+Pacific": 30,
				"DB+im+Internet/DB+Schenker+in+Belarus": 11,
				"DB+im+Internet/DB+Schenker+in+Belgi%C3%AB": 22,
				"DB+im+Internet/DB+Schenker+in+Belgium": 35,
				"DB+im+Internet/DB+Schenker+in+Brazil": 6,
				"DB+im+Internet/DB+Schenker+in+Cambodia": 6,
				"DB+im+Internet/DB+Schenker+in+Canada": 30,
				"DB+im+Internet/DB+Schenker+in+China": 19,
				"DB+im+Internet/DB+Schenker+in+Denmark": 18,
				"DB+im+Internet/DB+Schenker+in+Egypt": 40,
				"DB+im+Internet/DB+Schenker+in+Estonia": 70,
				"DB+im+Internet/DB+Schenker+in+Finland": 1,
				"DB+im+Internet/DB+Schenker+in+Guatemala": 4,
				"DB+im+Internet/DB+Schenker+in+Hungary": 3,
				"DB+im+Internet/DB+Schenker+in+India": 9,
				"DB+im+Internet/DB+Schenker+in+Ireland": 1,
				"DB+im+Internet/DB+Schenker+in+Kenya": 39,
				"DB+im+Internet/DB+Schenker+in+Korea": 10,
				"DB+im+Internet/DB+Schenker+in+Latin+America": 3,
				"DB+im+Internet/DB+Schenker+in+Lithuania": 30,
				"DB+im+Internet/DB+Schenker+in+Luxembourg": 7,
				"DB+im+Internet/DB+Schenker+in+Mexico": 6,
				"DB+im+Internet/DB+Schenker+in+Oman": 40,
				"DB+im+Internet/DB+Schenker+in+Panama": 4,
				"DB+im+Internet/DB+Schenker+in+Philippines": 45,
				"DB+im+Internet/DB+Schenker+in+Portugal": 13,
				"DB+im+Internet/DB+Schenker+in+Saudi+Arabia": 13,
				"DB+im+Internet/DB+Schenker+in+Serbia": 4,
				"DB+im+Internet/DB+Schenker+in+Singapore": 18,
				"DB+im+Internet/DB+Schenker+in+Slovakia": 13,
				"DB+im+Internet/DB+Schenker+in+Spain": 2,
				"DB+im+Internet/DB+Schenker+in+Switzerland": 17,
				"DB+im+Internet/DB+Schenker+in+Thailand": 47,
				"DB+im+Internet/DB+Schenker+in+UAE": 4,
				"DB+im+Internet/DB+Schenker+in+Ukraine": 26,
				"DB+im+Internet/DB+Schenker+in+Venezuela+": 7,
				"DB+im+Internet/DB+Schenker+in+Vietnam+%7C+Ocean+Freight+-+Air+Freight+-+Fairs+%26+Exhibitions": 42,
				"DB+im+Internet/DB+Schenker+in+der+Schweiz": 12,
				"DB+im+Internet/DB+Schenker+in+the+USA": 54,
				"DB+im+Internet/DB+Schenker+na+Slovensku": 1,
				"DB+im+Internet/DB+Schenker+no+Brasil": 6,
				"DB+im+Internet/DB+Schenker+u+Srbiji": 2,
				"DB+im+Internet/DB+Station+%26+Service": 5,
				"DB+im+Internet/DB+Systel+-+Konzerntreff+2016": 2,
				"DB+im+Internet/DB+Systel+GmbH": 18,
				"DB+im+Internet/DB+Systel+GmbH+": 9,
				"DB+im+Internet/DB+Systemtechnik": 350,
				"DB+im+Internet/DB+Training%2C+Learning+%26+Consulting": 15,
				"DB+im+Internet/DB+Zeitarbeit": 1,
				"DB+im+Internet/Deutsche+Bahn": 55,
				"DB+im+Internet/Deutsche+Bahn+-+2013+Annual+Report": 18,
				"DB+im+Internet/Deutsche+Bahn+-+Gesch%C3%A4ftsbericht+2013": 8,
				"DB+im+Internet/Deutsche+Bahn+-+Interim+Report+January+-+June+2014": 4,
				"DB+im+Internet/Deutsche+Bahn+Stiftung": 2,
				"DB+im+Internet/ESG+2014": 8,
				"DB+im+Internet/Elbe-Saale-Bahn": 2,
				"DB+im+Internet/Enterprise+Content+Management": 3,
				"DB+im+Internet/Etihad+Rail+DB": 2,
				"DB+im+Internet/Euro+Cargo+Rail": 8,
				"DB+im+Internet/FB-Community": 51,
				"DB+im+Internet/Home+-+DB+Schenker+in+Indonesia": 45,
				"DB+im+Internet/Infrastrukturportal": 34,
				"DB+im+Internet/Intermodal": 2,
				"DB+im+Internet/Investor+Relations": 71,
				"DB+im+Internet/Investor+Relations+DB+AG": 133,
				"DB+im+Internet/L%C3%A4rmschutzportal": 8,
				"DB+im+Internet/PopUpStore": 1,
				"DB+im+Internet/Portal+F": 2,
				"DB+im+Internet/S-Bahn+Stuttgart": 5,
				"DB+im+Internet/SUSSTATION": 13,
				"DB+im+Internet/Schenker+Deutschland+AG": 30,
				"DB+im+Internet/Schenker+Logistics+Nederland": 9,
				"DB+im+Internet/Schenker-Seino+Co.%2C+Ltd.": 7,
				"DB+im+Internet/ServiceStore+DB": 1,
				"DB+im+Internet/Suomen+DB+Schenker": 5,
				"DB+im+Internet/Symposium+Competition+%26+Regulation": 2,
				"DB+im+Internet/Transfesa": 1,
				"DB+im+Internet/Vorstandsinformationsportal": 2,
				"DB+im+Internet/Wettbewerbssymposium": 2,
				"DB+im+Internet/Zukunft+Deutsche+Bahn": 18,
				"EinkaufsWiki": 433,
				"EinkaufsWiki/EinkaufsWiki": 191,
				"EinkaufsWiki/Institute+of+Procurement": 6,
				"EinkaufsWiki/Katalog+der+Dienstleistungen+im+DB-Konzern": 9,
				"EinkaufsWiki/T-Wiki": 220,
				"EinkaufsWiki/TE-MD": 7,
				"Intranet": 4062,
				"Intranet/%D0%98%D0%BD%D1%82%D1%80%D0%B0%D0%BD%D0%B5%D1%82+%D0%BD%D0%B0+%D0%A8%D0%B5%D0%BD%D0%BA%D0%B5%D1%80+%D0%95%D0%9E%D0%9E%D0%94": 17,
				"Intranet/Archivierung": 1,
				"Intranet/Bahn+Content+Management+-+Das+Dokumentenmanagement+System": 6,
				"Intranet/Bereitstellungszentrum+Nord": 3,
				"Intranet/Content+Management": 4,
				"Intranet/DB+Akademie": 2,
				"Intranet/DB+Enterprise+Cloud": 7,
				"Intranet/DB+Gastronomie": 1,
				"Intranet/DB+Management+Portal": 215,
				"Intranet/DB+Schenker+Americas+Intranet": 149,
				"Intranet/DB+Schenker+Asia+Pacific": 137,
				"Intranet/DB+Schenker+Australia": 189,
				"Intranet/DB+Schenker+Belgium": 82,
				"Intranet/DB+Schenker+China": 49,
				"Intranet/DB+Schenker+Denmark": 17,
				"Intranet/DB+Schenker+France+Intranet": 14,
				"Intranet/DB+Schenker+Greece": 10,
				"Intranet/DB+Schenker+Head+Office": 678,
				"Intranet/DB+Schenker+India": 41,
				"Intranet/DB+Schenker+Intranet+Lithuania": 10,
				"Intranet/DB+Schenker+Intranet+SEE": 81,
				"Intranet/DB+Schenker+Italy+-+Intranet": 44,
				"Intranet/DB+Schenker+Japan": 45,
				"Intranet/DB+Schenker+Latvia+Intranet": 30,
				"Intranet/DB+Schenker+Romania": 22,
				"Intranet/DB+Schenker+Singapore": 1,
				"Intranet/DB+Schenker+United+Kingdom": 133,
				"Intranet/DB+Schenker+in+Thailand": 36,
				"Intranet/DB+Schulkooperationen": 8,
				"Intranet/DB+Systel+GmbH": 172,
				"Intranet/DB+Systel+helps": 3,
				"Intranet/DB+Systel+hilft": 2,
				"Intranet/DB+Vertrieb": 3,
				"Intranet/DB-Management+Portal": 369,
				"Intranet/DB-Melder": 2,
				"Intranet/DB-net": 783,
				"Intranet/Digitalisierung+Netz": 3,
				"Intranet/ECM+Showcase+-+Ein+Portal": 4,
				"Intranet/Einfachbahn": 1,
				"Intranet/FAQ+Plattform+ETCS+Programm": 6,
				"Intranet/FZI+-+Produktions+IT": 6,
				"Intranet/FZI+Intranet": 7,
				"Intranet/GBR+DB+AG+Holding": 6,
				"Intranet/GBR+DB+Fernverkehr+AG": 3,
				"Intranet/GBR+DB+ProjektBau+GmbH": 1,
				"Intranet/GBR+DB+Regio%2FStadtverkehr": 6,
				"Intranet/GBR+DB+RegioNetz": 5,
				"Intranet/GBR+DB+Services": 3,
				"Intranet/GBR+DB+Sicherheit": 1,
				"Intranet/H44+wird+noch+besser": 2,
				"Intranet/HRconnects": 30,
				"Intranet/IT+Fernverkehr": 27,
				"Intranet/IT+Sicherheit": 4,
				"Intranet/Ideenmanagement": 1,
				"Intranet/Intranet+DB+Projekt+Stuttgart%E2%80%93Ulm+GmbH": 4,
				"Intranet/Intranet+DB+ProjektBau+GmbH": 15,
				"Intranet/Intranet+Ressort+Personal": 1,
				"Intranet/Intranet+Schenker+Switzerland": 27,
				"Intranet/Intranet+der+DB+Netz+AG": 20,
				"Intranet/Nova": 50,
				"Intranet/Plattformportal": 2,
				"Intranet/Portal+C": 3,
				"Intranet/Regionalnetze": 1,
				"Intranet/SAP+Portal": 33,
				"Intranet/SCHENKER+%26+CO+AG": 231,
				"Intranet/SCR-Lernportal": 5,
				"Intranet/SEPA": 4,
				"Intranet/Schenker+Logistics+Nederland": 79,
				"Intranet/Schwerbehindertenvertretungen": 3,
				"Intranet/Serviceteam+Online-Media": 4,
				"Intranet/Serviceteam+Online-Medien": 7,
				"Intranet/Small+Solutions": 1,
				"Intranet/Stephi": 8,
				"Intranet/Technischer+Netzzugang": 1,
				"Intranet/Trafo": 1,
				"Intranet/Vertriebs-+und+Fahrplanforum": 2,
				"Intranet/Werk+Krefeld": 1,
				"Intranet/iMan+%E2%80%93+Identity+Management": 18,
				"Intranet/iMan+%E2%80%93+zentrales+Benutzermanagement": 39,
				"Intranet/youropeWORK": 17,
				"KRWD": 47,
				"Mediathek": 114,
				"Notes+Datenbanken": 304,
				"Notes+Datenbanken/Bilanzierungshandbuch": 124,
				"Notes+Datenbanken/smartidee+Ideenbank": 180,
				"Prozessportal": 234,
				"Prozessportal/Cargo+DB+Cargo+AG": 10,
				"Prozessportal/Cargo+DB+Cargo+Logistics+GmbH": 5,
				"Prozessportal/Cargo+DB+Cargo+Schweiz+GmbH": 5,
				"Prozessportal/Cargo+DB+Intermodal+Services+GmbH": 5,
				"Prozessportal/DB+JobService": 2,
				"Prozessportal/DB+Netz2": 10,
				"Prozessportal/DB+Services": 21,
				"Prozessportal/DB+Services+Immo": 1,
				"Prozessportal/DB+Station+und+Service": 10,
				"Prozessportal/DB+Systel": 104,
				"Prozessportal/DB-Konzern": 55,
				"Prozessportal/Ressort+FE+Beschaffung": 5,
				"Prozessportal/Ressort+IQ+PrePub+SQMM": 1,
				"TIKA": 506,
				"TIKA/GA+SSC+-+Global+IT+Roll+Out": 45,
				"TIKA/GA+SSC+Training": 2,
				"TIKA/GPO+-+FBG1": 8,
				"TIKA/GPO+-+Official+Documents": 185,
				"TIKA/Global+Accounting+Conference": 2,
				"TIKA/Global+Accounting+SSC+PMO": 17,
				"TIKA/Muster+WA+%2F+WA+Example": 27,
				"TIKA/SSC+EU_General+Schenker+Logistics+RO": 2,
				"TIKA/SSC+EU_ISP7+Training": 9,
				"TIKA/SSC+EU_LL+CZ_AP": 8,
				"TIKA/SSC+EU_LL+CZ_AR": 4,
				"TIKA/SSC+EU_LL+ES_AP": 4,
				"TIKA/SSC+EU_LL+NL_AP": 3,
				"TIKA/SSC+EU_LL+RO_AP": 6,
				"TIKA/SSC+EU_LL+RO_GL": 6,
				"TIKA/TIKA+Support": 3,
				"TIKA/TIKA+intern": 120,
				"TIKA/TIKA_Training": 1,
				"TIKA/Templates_Roadmap": 15,
				"Wiki-Pool+DB+Systel": 8548,
				"Wiki-Pool+DB+Systel/%C2%BBMonitoring+2.0%C2%AB": 20,
				"Wiki-Pool+DB+Systel/AIDA+BINA": 7,
				"Wiki-Pool+DB+Systel/AVB+Wiki": 34,
				"Wiki-Pool+DB+Systel/Agile+Community": 60,
				"Wiki-Pool+DB+Systel/Agilisierung+Solution+Center": 3,
				"Wiki-Pool+DB+Systel/Application+und+Release+Management+Infrastructure+and+Holding+II": 2,
				"Wiki-Pool+DB+Systel/Applicationmanagement+Infrastructure": 1,
				"Wiki-Pool+DB+Systel/Arbeits-%2C+Gesundheits-%2C+Brand-+und+Umweltschutz": 25,
				"Wiki-Pool+DB+Systel/Archivierung": 3,
				"Wiki-Pool+DB+Systel/Athene+Nutzer+Info": 5,
				"Wiki-Pool+DB+Systel/Ausbildung": 3,
				"Wiki-Pool+DB+Systel/Ausbildung+Infrastruktur": 4,
				"Wiki-Pool+DB+Systel/Automatenzentrum+Wiki": 24,
				"Wiki-Pool+DB+Systel/Automation": 218,
				"Wiki-Pool+DB+Systel/Availability+Managment+und+Reporting": 16,
				"Wiki-Pool+DB+Systel/B2.0+Haus+4+und+BiesdorfUmz%C3%BCge+%28HuBU%29": 7,
				"Wiki-Pool+DB+Systel/BASE": 251,
				"Wiki-Pool+DB+Systel/BAzubi-Labor": 7,
				"Wiki-Pool+DB+Systel/BF+Doku+VM-Tool": 12,
				"Wiki-Pool+DB+Systel/Barrierefreiheit": 8,
				"Wiki-Pool+DB+Systel/Bereichs-News": 5,
				"Wiki-Pool+DB+Systel/Blockchain": 2,
				"Wiki-Pool+DB+Systel/Business+Innovation+Management": 73,
				"Wiki-Pool+DB+Systel/Business+Intelligence": 17,
				"Wiki-Pool+DB+Systel/Business+Workflow+on+Demand+%28BWoD%29": 17,
				"Wiki-Pool+DB+Systel/Button+Portal": 1,
				"Wiki-Pool+DB+Systel/CRM+DBS+Wiki": 12,
				"Wiki-Pool+DB+Systel/CRM_SuperOffice": 19,
				"Wiki-Pool+DB+Systel/Carmen+-+Tosca": 218,
				"Wiki-Pool+DB+Systel/Changemanagement": 3,
				"Wiki-Pool+DB+Systel/Cloud-Community": 77,
				"Wiki-Pool+DB+Systel/Cockpit+Management": 7,
				"Wiki-Pool+DB+Systel/Content+Management": 28,
				"Wiki-Pool+DB+Systel/Continuous+Delivery+Dokumentation%3A+Architektur+und+Baupl%C3%A4ne": 41,
				"Wiki-Pool+DB+Systel/Customer+Centricity+Botschafter+Community": 1,
				"Wiki-Pool+DB+Systel/DB+Rapid+App": 2,
				"Wiki-Pool+DB+Systel/DB+Search": 58,
				"Wiki-Pool+DB+Systel/DB+Systel+Human+Resources": 7,
				"Wiki-Pool+DB+Systel/DB+Systel+SAP+SRM": 26,
				"Wiki-Pool+DB+Systel/DB+Systel+UK+Ltd+Wiki": 7,
				"Wiki-Pool+DB+Systel/DB+Systel+Wiki": 688,
				"Wiki-Pool+DB+Systel/DB+Systel+im+KundenServiceZentrum+von+DB+Schenker+Rail": 6,
				"Wiki-Pool+DB+Systel/DBNetzBetriebszentralen": 3,
				"Wiki-Pool+DB+Systel/DCS+-+Zentrales+Auftragsmanagement": 1,
				"Wiki-Pool+DB+Systel/DCS+Infos+und+FAQ": 4,
				"Wiki-Pool+DB+Systel/DCS+News": 190,
				"Wiki-Pool+DB+Systel/DIPI+TEAM+WIKI": 4,
				"Wiki-Pool+DB+Systel/Dataservices": 1,
				"Wiki-Pool+DB+Systel/DevOps": 107,
				"Wiki-Pool+DB+Systel/Dockerhub+Dokumentation": 3,
				"Wiki-Pool+DB+Systel/Duales+Studium": 12,
				"Wiki-Pool+DB+Systel/E-Werk+Algorithmus+Team": 1,
				"Wiki-Pool+DB+Systel/E2E": 2,
				"Wiki-Pool+DB+Systel/ECM+-+Know+How": 3,
				"Wiki-Pool+DB+Systel/ECM+Projekte": 211,
				"Wiki-Pool+DB+Systel/Einstiegsqualifizierung+DB+Systel": 3,
				"Wiki-Pool+DB+Systel/Exchange+Program+JR+Group": 11,
				"Wiki-Pool+DB+Systel/Fahrzeug-IT": 456,
				"Wiki-Pool+DB+Systel/Flexibles+Arbeiten": 3,
				"Wiki-Pool+DB+Systel/Forum+DB+Systel": 5,
				"Wiki-Pool+DB+Systel/GA+SSC+SeMa": 3,
				"Wiki-Pool+DB+Systel/Gr%C3%BCnes+Backlog+Test-Wiki": 3,
				"Wiki-Pool+DB+Systel/HPI+Studies": 33,
				"Wiki-Pool+DB+Systel/Hilfe": 27,
				"Wiki-Pool+DB+Systel/I.LVD+42": 5,
				"Wiki-Pool+DB+Systel/ICT+Beratung": 5,
				"Wiki-Pool+DB+Systel/ICT+Management+%40+DB+Systel": 20,
				"Wiki-Pool+DB+Systel/ICT-OM": 6,
				"Wiki-Pool+DB+Systel/ICT-Operations+Management": 3,
				"Wiki-Pool+DB+Systel/IFS1+-+Billing": 2,
				"Wiki-Pool+DB+Systel/INet+BF": 1,
				"Wiki-Pool+DB+Systel/ISIS-Projektwiki": 1,
				"Wiki-Pool+DB+Systel/ISTP+DevOps": 8,
				"Wiki-Pool+DB+Systel/IT+Common+Services": 1,
				"Wiki-Pool+DB+Systel/IT+Operations+Management": 2,
				"Wiki-Pool+DB+Systel/IT-Fabrik": 11,
				"Wiki-Pool+DB+Systel/ImProW": 8,
				"Wiki-Pool+DB+Systel/Info-Buffet": 14,
				"Wiki-Pool+DB+Systel/Infrastructure+Visualisation+%26+Planning": 37,
				"Wiki-Pool+DB+Systel/Insourcing+%26+Optimization": 6,
				"Wiki-Pool+DB+Systel/Internet+of+Things": 3,
				"Wiki-Pool+DB+Systel/IntraCloud": 40,
				"Wiki-Pool+DB+Systel/JIRA+as+a+Service": 4,
				"Wiki-Pool+DB+Systel/KI-Community": 7,
				"Wiki-Pool+DB+Systel/Kommunikation+Services": 50,
				"Wiki-Pool+DB+Systel/LCM+Transportation+%26+Logistics": 2,
				"Wiki-Pool+DB+Systel/LMSlab": 83,
				"Wiki-Pool+DB+Systel/Leistungsportfolio": 1,
				"Wiki-Pool+DB+Systel/Lizenzierung+von+Software": 15,
				"Wiki-Pool+DB+Systel/Logistic+4.0%40DB+SR+Infrastructure": 26,
				"Wiki-Pool+DB+Systel/LuFV-IT%3A+Leistungs-+und+Finanzierungsvereinbarung+IT": 8,
				"Wiki-Pool+DB+Systel/Managed+Environment": 46,
				"Wiki-Pool+DB+Systel/Managed+Workplace": 9,
				"Wiki-Pool+DB+Systel/Metis": 2,
				"Wiki-Pool+DB+Systel/Minerva": 433,
				"Wiki-Pool+DB+Systel/Mobile+Solutions+Community": 234,
				"Wiki-Pool+DB+Systel/Mobilfunk": 5,
				"Wiki-Pool+DB+Systel/Mobilfunkmigration": 2,
				"Wiki-Pool+DB+Systel/Monitoring+Personenverkehr+T.SVL+1": 14,
				"Wiki-Pool+DB+Systel/MyDBSystel+-+Business+Service+Provisioning+Plattform": 1,
				"Wiki-Pool+DB+Systel/NVS": 39,
				"Wiki-Pool+DB+Systel/NetzBF": 2,
				"Wiki-Pool+DB+Systel/Open+Data": 2,
				"Wiki-Pool+DB+Systel/Open+Source+Community": 4,
				"Wiki-Pool+DB+Systel/Operational+Intelligence": 9,
				"Wiki-Pool+DB+Systel/Operations+Planning+%26+Management": 1,
				"Wiki-Pool+DB+Systel/Oracle+CRM": 9,
				"Wiki-Pool+DB+Systel/PPSFR": 2,
				"Wiki-Pool+DB+Systel/PSC": 1,
				"Wiki-Pool+DB+Systel/PSS+Team.Wiki": 2,
				"Wiki-Pool+DB+Systel/Portfolio+%26+Innovation+Team+Wiki": 1,
				"Wiki-Pool+DB+Systel/PrIMa": 95,
				"Wiki-Pool+DB+Systel/ProcLib+KVP": 6,
				"Wiki-Pool+DB+Systel/ProduktManagement+RiM": 27,
				"Wiki-Pool+DB+Systel/Programm+1+%22Order+to+Cash%22": 2,
				"Wiki-Pool+DB+Systel/Projekt+%C3%9C+12": 11,
				"Wiki-Pool+DB+Systel/Projekt+ECM": 529,
				"Wiki-Pool+DB+Systel/Projekt+EPS": 17,
				"Wiki-Pool+DB+Systel/Projekt+KVD": 17,
				"Wiki-Pool+DB+Systel/Projekt+MTx": 1,
				"Wiki-Pool+DB+Systel/Projekt+PlanET": 28,
				"Wiki-Pool+DB+Systel/Projekt-KTR-Abl%C3%B6sung": 3,
				"Wiki-Pool+DB+Systel/Projektdokumentation+des+Solution+Center+Mobile": 1,
				"Wiki-Pool+DB+Systel/Projektwiki+RiM": 29,
				"Wiki-Pool+DB+Systel/QT+LuP": 2,
				"Wiki-Pool+DB+Systel/Redaktionsteam+Ver%C3%A4nderungskommunikation": 1,
				"Wiki-Pool+DB+Systel/Reisebuddy": 25,
				"Wiki-Pool+DB+Systel/Releasemanagement+Wiki": 11,
				"Wiki-Pool+DB+Systel/ReportIT+Wiki": 4,
				"Wiki-Pool+DB+Systel/Requestmanagement": 263,
				"Wiki-Pool+DB+Systel/RunIT+2.i": 16,
				"Wiki-Pool+DB+Systel/SC+Instandhaltung": 138,
				"Wiki-Pool+DB+Systel/SC+Schedule+Systems": 629,
				"Wiki-Pool+DB+Systel/SOA%40DB": 26,
				"Wiki-Pool+DB+Systel/SVS+Wiki": 22,
				"Wiki-Pool+DB+Systel/Sarasvati": 55,
				"Wiki-Pool+DB+Systel/Schenker+Logistics+Wiki": 254,
				"Wiki-Pool+DB+Systel/Schlog+Monitoring": 23,
				"Wiki-Pool+DB+Systel/Schwerbehindertenvertretung": 6,
				"Wiki-Pool+DB+Systel/Security": 10,
				"Wiki-Pool+DB+Systel/Security+Operations": 14,
				"Wiki-Pool+DB+Systel/Service+Delivery+Manual": 28,
				"Wiki-Pool+DB+Systel/Skill-+und+Ressourcenmanagement": 16,
				"Wiki-Pool+DB+Systel/Skydeck": 58,
				"Wiki-Pool+DB+Systel/Small+Solutions": 3,
				"Wiki-Pool+DB+Systel/Social+Business": 6,
				"Wiki-Pool+DB+Systel/Solution+Center+Infrastructure+Management": 9,
				"Wiki-Pool+DB+Systel/Solution+Center+Personalsysteme": 3,
				"Wiki-Pool+DB+Systel/Solution+Center+Reisendeninformationssysteme": 254,
				"Wiki-Pool+DB+Systel/Solution+Group+DB+Schenker+Rail": 264,
				"Wiki-Pool+DB+Systel/Sourcing+Wiki": 1,
				"Wiki-Pool+DB+Systel/Step42": 290,
				"Wiki-Pool+DB+Systel/Strategie+DB+Systel": 71,
				"Wiki-Pool+DB+Systel/Suppliermanagement": 1,
				"Wiki-Pool+DB+Systel/TM1+Systeme": 22,
				"Wiki-Pool+DB+Systel/Tarifwegeermittlung%3A+TWE2": 32,
				"Wiki-Pool+DB+Systel/Technologietag+DB+Systel": 2,
				"Wiki-Pool+DB+Systel/Technology+Board": 5,
				"Wiki-Pool+DB+Systel/Test+Integration+Center": 30,
				"Wiki-Pool+DB+Systel/Test-Factory+Netze+Fahrplansysteme": 3,
				"Wiki-Pool+DB+Systel/Testautomation": 149,
				"Wiki-Pool+DB+Systel/Testspace": 176,
				"Wiki-Pool+DB+Systel/Thales+Move+2013": 32,
				"Wiki-Pool+DB+Systel/Tool+Management": 91,
				"Wiki-Pool+DB+Systel/Transformation": 9,
				"Wiki-Pool+DB+Systel/Transformationsboard+der+DB+Systel": 5,
				"Wiki-Pool+DB+Systel/UDG": 92,
				"Wiki-Pool+DB+Systel/UX+Community": 7,
				"Wiki-Pool+DB+Systel/UX+Space": 24,
				"Wiki-Pool+DB+Systel/VIP-Service": 2,
				"Wiki-Pool+DB+Systel/Value+IT+-+Projekt-Delivery": 1,
				"Wiki-Pool+DB+Systel/Verbundtarifierung+und+-kontrolle": 1,
				"Wiki-Pool+DB+Systel/Verfahren-MAXX": 39,
				"Wiki-Pool+DB+Systel/Verteile+Fertigung+-Global+Sourcing": 6,
				"Wiki-Pool+DB+Systel/WIS-Wiki": 1,
				"Wiki-Pool+DB+Systel/Wiki+Personenverkehr": 14,
				"Wiki-Pool+DB+Systel/WorldInsight": 1,
				"Wiki-Pool+DB+Systel/ZAS+-+Zentrale+Auftragssteuerung": 5,
				"Wiki-Pool+DB+Systel/ZEBRA": 8,
				"Wiki-Pool+DB+Systel/Zentrales+Monitoring": 4,
				"Wiki-Pool+DB+Systel/assistify": 7,
				"Wiki-Pool+DB+Systel/connect": 3,
				"Wiki-Pool+DB+Systel/docker+Community": 35,
				"Wiki-Pool+DB+Systel/eSuite+%26+RailServer": 105,
				"Wiki-Pool+DB+Systel/eTicket+%28%28%28e": 2,
				"Wiki-Pool+DB+Systel/middleware": 15,
				"Wiki-Pool+DB+Systel/scot-wiki": 38,
				"Wiki-Pool+DB+Systel/sid": 15,
				"ZRWD": 407
			},
			"dbsearch_author_ss": {
				"Andrea Brandt": 407,
				"Katja Lutherdt": 164,
				"Michael Binzen": 130,
				"Ronald Bieber": 115,
				"Sven Oschelewski": 114,
				"Lars Tiedermann": 111,
				"Dorit Baumeister": 92,
				"Sebastian Se Schmidt": 84,
				"Markus Schlun": 82,
				"Martin Strunk": 79,
				"Natascha Brosche": 79,
				"Ulrich Heinl": 78,
				"Stefan Hook": 77,
				"Marianne Girchott": 76,
				"Chris Walter": 75,
				"Toni Krevet": 73,
				"Unbekannter Benutzer (florianhuster)": 71,
				"Detlef Winkler": 70,
				"Oliver J‰gle": 70,
				"Markus Schuch": 69,
				"": 127097
			},
			"dbsearch_keywords_ss": {
				"test": 122,
				"release": 103,
				"meeting-notes": 98,
				"news": 96,
				"Allgemein": 83,
				"eip": 69,
				"kb-how-to-article": 57,
				"lpa": 54,
				"lpa8": 50,
				"ilpa8": 48,
				"retrospective": 30,
				"protokoll": 29,
				"sap": 23,
				"performancetest": 21,
				"tmt": 21,
				"Qualit‰t": 20,
				"prcbb": 20,
				"dcs_news": 18,
				"maxx": 18,
				"qatc": 17
			},
			"dbsearch_content_type_aggregated_s": {
				"msword": 64189,
				"msexcel": 30134,
				"pdf": 18290,
				"mspowerpoint": 12074,
				"html": 10209,
				"text": 2749,
				"compressed": 1009,
				"richtext": 436,
				"notes": 254,
				"msproject": 34
			}
		},
		"facet_dates": {},
		"facet_ranges": {}
	},
	"highlighting": {
		"https://dbsystel.wiki.intranet.deutschebahn.com/wiki/pages/viewpage.action?pageId=57855715": {},
		"https://m00014.sharepoint.noncd.rz.db.de/workingareas/musterwawaexample/Documents/Projekt%202/Test%20Anna%2023.pdf": {"dbsearch_highlight_t_de": ["<strong>Test</strong> Anna 23 Anna 01.03.2017 Mit Kommentaren am 10.03.2017 Und noch mehr Kommentare am 10.03.2017"]},
		"https://m00014.sharepoint.noncd.rz.db.de/workingareas/musterwawaexample/Documents/Projekt%202/Test%20Anna%2023.docx": {"dbsearch_highlight_t_de": ["<strong>Test</strong> Anna 23 Anna 01.03.2017 Mit Kommentaren am 10.03.2017 Und noch mehr Kommentare am 10.03.2017"]},
		"https://athene.intranet.deutschebahn.com/athene/livelink?func=ll&objAction=overview&objID=25748005": {"dbsearch_highlight_t_de": ["f¸r das <strong>Testen</strong> der Funktionsf‰higkeit nach einem Betriebssystem-Update angelegt. tempor‰r f¸r <strong>Test</strong> Para", "&#x2F;app&#x2F;paisycs&#x2F;archiv&#x2F;bin&#x2F;create_baseline P14B N+10y # <strong>TMT</strong> 697 Testlauf Verzeichnispflege Output_SST_archiv"]},
		"https://dbsystel.wiki.intranet.deutschebahn.com/wiki/pages/viewpage.action?pageId=57850201": {"dbsearch_highlight_t_de": ["Teilnehmer † Agenda des Meetings Begr¸ﬂung CA <strong>Test</strong> ZPM <strong>Test</strong> Vorstellung neuer MA (Alexander Hitz) Offene", "Protokollpunkt ToDos Verantwortlich Endtermin 1 Stand CA <strong>Test</strong> Bereitstellen Markwart 22.02.2017 2 Stand ZPM Test"]},
		"https://dbsystel.wiki.intranet.deutschebahn.com/wiki/pages/viewpage.action?pageId=56552993": {"dbsearch_highlight_t_de": ["Kurzinfo MAB Folgeworkshops (Christina Herweg) CA <strong>Test</strong> Vorstellung Neuer Mitarbeiter (Hossein Rabighomi", "nkt ToDos Verantwortlich Endtermin 1 Roadmap CA <strong>Test</strong> 2017 Bereitstellen Markwart 26.01.2017 2 Informationen"]},
		"https://athene.intranet.deutschebahn.com/athene/livelink?func=ll&objAction=overview&objID=27775601": {},
		"https://athene.intranet.deutschebahn.com/athene/livelink?func=ll&objAction=overview&objID=27761612": {}
	},
	"spellcheck": {"suggestions": {"correctlySpelled": true}},
	"debug": {
		"timing": {
			"time": 1430.0,
			"prepare": {
				"time": 13.0,
				"query": {"time": 1.0},
				"facet": {"time": 0.0},
				"mlt": {"time": 0.0},
				"highlight": {"time": 0.0},
				"stats": {"time": 0.0},
				"spellcheck": {"time": 0.0},
				"dynamicElevator": {"time": 1.0},
				"elevator": {"time": 0.0},
				"manifoldCFSecurity": {"time": 11.0},
				"dbsearchPreFilter": {"time": 0.0},
				"dbsearchTimeFilter": {"time": 0.0},
				"debug": {"time": 0.0}
			},
			"process": {
				"time": 1417.0,
				"query": {"time": 1139.0},
				"facet": {"time": 261.0},
				"mlt": {"time": 0.0},
				"highlight": {"time": 17.0},
				"stats": {"time": 0.0},
				"spellcheck": {"time": 0.0},
				"dynamicElevator": {"time": 0.0},
				"elevator": {"time": 0.0},
				"manifoldCFSecurity": {"time": 0.0},
				"dbsearchPreFilter": {"time": 0.0},
				"dbsearchTimeFilter": {"time": 0.0},
				"debug": {"time": 0.0}
			}
		}
	}
};
