#!/bin/bash

# Config options for Caddyfile
options="protocol siteurl port"

create_caddyfile(){
# Copy template to config Caddyfile
cp $SNAP/bin/Caddyfile $SNAP_DATA/Caddyfile

}

update_caddyfile(){

# Config file path for Caddyfile
Caddyfile=$SNAP_DATA/Caddyfile

# add or replace an option inside the config file. Create the file if doesn't exist
refresh_opt_in_config() {
    opt=$1
    value="$2"
    if $(grep -q "_${opt}_" $Caddyfile); then
        sed "s/_${opt}_/$value/" $Caddyfile 2>/dev/null > ${Caddyfile}.new
        mv -f ${Caddyfile}.new $Caddyfile 2>/dev/null
    else
        echo "Fail to update $opt in Caddyfile" 
    fi
}

# Iterate through the config options array
for opt in $options
    do
    # Use snapctl to get the value registered by the snap set command
    refresh_opt_in_config $opt $(snapctl get $opt)
done

}

create_caddy
update_caddyfile

