#!/bin/sh
rm -rf $SNAP_DATA/dump
rm $SNAP_DATA/backup.tgz
mkdir $SNAP_DATA/dump
mongodump -d parties -o $SNAP_DATA/dump
tar zcvf $SNAP_DATA/backup.tgz  $SNAP_DATA/dump
echo "A backup of your data can be found at $SNAP_DATA/backup.tgz"
