FROM nginx:alpine

RUN rm -rf /etc/nginx/conf.d/*

COPY dist/nginx.conf /etc/nginx/conf.d/default.conf

RUN rm -f dist/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

COPY dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
