# .github/workflows/ci-preview-deploy.yml
name: Deploy GitHub Pages
concurrency: preview-deploy-${{ github.ref }}
on:
  push:
    branches:
      - main
      - master
      - develop
jobs:
  deploy-preview:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: rharkor/caching-for-turbo@564b6d155a4aec5ada97411ba7f7956e4bac890a # v2.4.0

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          cache-modules: true
          install: true

      - name: Build
        run: |
          yarn turbo run build-preview
          yarn turbo run .:build-preview-move
          npx indexifier .preview --html  --extensions .html  > .preview/index.html
          mv .preview ${{ github.ref_name }}
          mkdir .preview
          mv ${{ github.ref_name }} .preview

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .preview
          keep_files: true
