name: Test Storybook

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      deno-version:
        required: true
        type: string

    secrets:
      CODECOV_TOKEN:
        required: true
      NPM_TOKEN:
        required: false

env:
  TOOL_NODE_FLAGS: ${{ vars.TOOL_NODE_FLAGS }}

jobs:
  test:
    runs-on: ubuntu-24.04-arm

    name: Test Storybook

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ inputs.node-version }}
          deno-version: ${{ inputs.deno-version }}
          cache-modules: true
          install: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: rharkor/caching-for-turbo@2f61e9bebb2f51f2ed041ce70377b0f81b3b1e0d # v2.4.1

      - uses: ./.github/actions/restore-packages

      - uses: ./.github/actions/setup-playwright

      - name: Run tests
        run: yarn test-storybook
        env:
          STORYBOOK_DISABLE_TELEMETRY: 1

      - uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          flags: unit
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
