name: 'Release PR Description'

on:
  pull_request:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-pr:
    runs-on: ubuntu-24.04
    if: startsWith(github.head_ref, 'release-')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_PAT }}

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          cache-modules: true
          install: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: rharkor/caching-for-turbo@00a0515f175df9fd2e15c4560144ad5fdbebb0c7 # v2.3.13

      - name: Build packages
        run: yarn build

      - name: Update PR description
        uses: ./packages/release-action
        with:
          action: update-pr-description
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}
