name: Start patch release

on:
  repository_dispatch:
    types: ['release-patch']
# workflow_dispatch:
#   inputs:
#   base-ref:
#     description: Base version
#     default: develop
#     required: false
#     type: string

jobs:
  release:
    uses: ./.github/workflows/release-manual.yml
    with:
      action: patch
      base-ref: ${{ github.event.client_payload.base-ref || 'develop' }}
    secrets: inherit
