name: Cut release

on:
  repository_dispatch:
    types: ['release-cut']

jobs:
  release:
    uses: ./.github/workflows/release-manual.yml
    with:
      action: cut
      base-ref: ${{ github.event.client_payload['base-ref'] || 'develop' }}
    secrets:
      CI_PAT: ${{ secrets.CI_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
