name: Visual Regression Testing

on:
  push:
    paths:
      - 'src/components/**'
      - 'stories/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run storybook &
      - run: sleep 15
      - run: npm run loki:test
