const relevantKeys = [
	'Unique-ID',
	'Event-Name',
	'Event-Sequence',
	'Event-Date-GMT',
	'Call-Direction',
	'Channel-HIT-Dialplan',
	'Channel-Presence-ID',
	'Channel-Call-UUID',
	'Caller-Direction',
	'Caller-Logical-Direction',
	'Caller-Username',
	'Caller-Caller-ID-Name',
	'Caller-Caller-ID-Number',
	'Caller-Orig-Caller-ID-Number',
	'Caller-ANI',
	'Caller-Destination-Number',
	'Caller-Unique-ID',
	'Caller-Channel-Name',
	'Presence-Call-Direction',
	'Channel-Name',
	'Caller-Callee-ID-Name',
	'Caller-Callee-ID-Number',
	'Channel-Call-State',

	'Other-Type',
	'Other-Leg-Direction',
	'Other-Leg-Logical-Direction',
	'Other-Leg-Username',
	'Other-Leg-Caller-ID-Number',
	'Other-Leg-Orig-Caller-ID-Number',
	'Other-Leg-ANI',
	'Other-Leg-Destination-Number',
	'Other-Leg-Unique-ID',
	'Other-Leg-RDNIS',

	'Bridge-A-Unique-ID',
	'Bridge-B-Unique-ID',

	'variable_sip_from_user',
	'variable_call_uuid',
	'variable_sip_call_id',
	'variable_accountcode',
	'variable_effective_caller_id_number',
	'variable_user_name',
	'variable_sip_from_user_stripped',
	'variable_sip_from_tag',
	'variable_sip_req_user',
	'variable_sip_to_user',
	'variable_sip_contact_user',
	'variable_presence_id',
	'variable_direction',
	'variable_uuid',
	'variable_sip_profile_name',
	'variable_originator',
	'variable_dialed_user',
	'variable_dialed_extension',
	'variable_originating_leg_uuid',
	'variable_bridge_uuid',
];

export function getRelevantRawData(raw: Record<string, string>): Record<string, string> {
	return Object.fromEntries(Object.entries(raw).filter(([key]) => relevantKeys.includes(key) || key.includes('RocketChat')));
}
